
class dict:
  dictionary={

"__assert_fail":"void",
"__assert_perror_fail":"void",
"__assert":"void",
"__ctype_b_loc":"const unsigned short **",
"__ctype_tolower_loc":"const __int32_t **",
"__ctype_toupper_loc":"const __int32_t **",
"isalnum":"int",
"isalpha":"int",
"iscntrl":"int",
"isdigit":"int",
"islower":"int",
"isgraph":"int",
"isprint":"int",
"ispunct":"int",
"isspace":"int",
"isupper":"int",
"isxdigit":"int",
"tolower":"int",
"toupper":"int",
"isblank":"int",
"isascii":"int",
"toascii":"int",
"_toupper":"int",
"_tolower":"int",
"isalnum_l":"int",
"isalpha_l":"int",
"iscntrl_l":"int",
"isdigit_l":"int",
"islower_l":"int",
"isgraph_l":"int",
"isprint_l":"int",
"ispunct_l":"int",
"isspace_l":"int",
"isupper_l":"int",
"isxdigit_l":"int",
"isblank_l":"int",
"__tolower_l":"int",
"tolower_l":"int",
"__toupper_l":"int",
"toupper_l":"int",
"__errno_location":"int *",
"setlocale":"char *",
"localeconv":"struct lconv *",
"newlocale":"locale_t",
"duplocale":"locale_t",
"freelocale":"void",
"uselocale":"locale_t",
"__fpclassify":"int",
"__signbit":"int",
"__isinf":"int",
"__finite":"int",
"__isnan":"int",
"__iseqsig":"int",
"__issignaling":"int",
"acos":"double",
"__acos":"double",
"asin":"double",
"__asin":"double",
"atan":"double",
"__atan":"double",
"atan2":"double",
"__atan2":"double",
"cos":"double",
"__cos":"double",
"sin":"double",
"__sin":"double",
"tan":"double",
"__tan":"double",
"cosh":"double",
"__cosh":"double",
"sinh":"double",
"__sinh":"double",
"tanh":"double",
"__tanh":"double",
"acosh":"double",
"__acosh":"double",
"asinh":"double",
"__asinh":"double",
"atanh":"double",
"__atanh":"double",
"exp":"double",
"__exp":"double",
"frexp":"double",
"__frexp":"double",
"ldexp":"double",
"__ldexp":"double",
"log":"double",
"__log":"double",
"log10":"double",
"__log10":"double",
"modf":"double",
"__modf":"double",
"expm1":"double",
"__expm1":"double",
"log1p":"double",
"__log1p":"double",
"logb":"double",
"__logb":"double",
"exp2":"double",
"__exp2":"double",
"log2":"double",
"__log2":"double",
"pow":"double",
"__pow":"double",
"sqrt":"double",
"__sqrt":"double",
"hypot":"double",
"__hypot":"double",
"cbrt":"double",
"__cbrt":"double",
"ceil":"double",
"__ceil":"double",
"fabs":"double",
"__fabs":"double",
"floor":"double",
"__floor":"double",
"fmod":"double",
"__fmod":"double",
"isinf":"int",
"finite":"int",
"drem":"double",
"__drem":"double",
"significand":"double",
"__significand":"double",
"copysign":"double",
"__copysign":"double",
"nan":"double",
"__nan":"double",
"isnan":"int",
"j0":"double",
"__j0":"double",
"j1":"double",
"__j1":"double",
"jn":"double",
"__jn":"double",
"y0":"double",
"__y0":"double",
"y1":"double",
"__y1":"double",
"yn":"double",
"__yn":"double",
"erf":"double",
"__erf":"double",
"erfc":"double",
"__erfc":"double",
"lgamma":"double",
"__lgamma":"double",
"tgamma":"double",
"__tgamma":"double",
"gamma":"double",
"__gamma":"double",
"lgamma_r":"double",
"__lgamma_r":"double",
"rint":"double",
"__rint":"double",
"nextafter":"double",
"__nextafter":"double",
"nexttoward":"double",
"__nexttoward":"double",
"remainder":"double",
"__remainder":"double",
"scalbn":"double",
"__scalbn":"double",
"ilogb":"int",
"__ilogb":"int",
"scalbln":"double",
"__scalbln":"double",
"nearbyint":"double",
"__nearbyint":"double",
"round":"double",
"__round":"double",
"trunc":"double",
"__trunc":"double",
"remquo":"double",
"__remquo":"double",
"lrint":"long",
"__lrint":"long",
"llrint":"long long",
"__llrint":"long long",
"lround":"long",
"__lround":"long",
"llround":"long long",
"__llround":"long long",
"fdim":"double",
"__fdim":"double",
"fmax":"double",
"__fmax":"double",
"fmin":"double",
"__fmin":"double",
"fma":"double",
"__fma":"double",
"scalb":"double",
"__scalb":"double",
"__fpclassifyf":"int",
"__signbitf":"int",
"__isinff":"int",
"__finitef":"int",
"__isnanf":"int",
"__iseqsigf":"int",
"__issignalingf":"int",
"acosf":"float",
"__acosf":"float",
"asinf":"float",
"__asinf":"float",
"atanf":"float",
"__atanf":"float",
"atan2f":"float",
"__atan2f":"float",
"cosf":"float",
"__cosf":"float",
"sinf":"float",
"__sinf":"float",
"tanf":"float",
"__tanf":"float",
"coshf":"float",
"__coshf":"float",
"sinhf":"float",
"__sinhf":"float",
"tanhf":"float",
"__tanhf":"float",
"acoshf":"float",
"__acoshf":"float",
"asinhf":"float",
"__asinhf":"float",
"atanhf":"float",
"__atanhf":"float",
"expf":"float",
"__expf":"float",
"frexpf":"float",
"__frexpf":"float",
"ldexpf":"float",
"__ldexpf":"float",
"logf":"float",
"__logf":"float",
"log10f":"float",
"__log10f":"float",
"modff":"float",
"__modff":"float",
"expm1f":"float",
"__expm1f":"float",
"log1pf":"float",
"__log1pf":"float",
"logbf":"float",
"__logbf":"float",
"exp2f":"float",
"__exp2f":"float",
"log2f":"float",
"__log2f":"float",
"powf":"float",
"__powf":"float",
"sqrtf":"float",
"__sqrtf":"float",
"hypotf":"float",
"__hypotf":"float",
"cbrtf":"float",
"__cbrtf":"float",
"ceilf":"float",
"__ceilf":"float",
"fabsf":"float",
"__fabsf":"float",
"floorf":"float",
"__floorf":"float",
"fmodf":"float",
"__fmodf":"float",
"isinff":"int",
"finitef":"int",
"dremf":"float",
"__dremf":"float",
"significandf":"float",
"__significandf":"float",
"copysignf":"float",
"__copysignf":"float",
"nanf":"float",
"__nanf":"float",
"isnanf":"int",
"j0f":"float",
"__j0f":"float",
"j1f":"float",
"__j1f":"float",
"jnf":"float",
"__jnf":"float",
"y0f":"float",
"__y0f":"float",
"y1f":"float",
"__y1f":"float",
"ynf":"float",
"__ynf":"float",
"erff":"float",
"__erff":"float",
"erfcf":"float",
"__erfcf":"float",
"lgammaf":"float",
"__lgammaf":"float",
"tgammaf":"float",
"__tgammaf":"float",
"gammaf":"float",
"__gammaf":"float",
"lgammaf_r":"float",
"__lgammaf_r":"float",
"rintf":"float",
"__rintf":"float",
"nextafterf":"float",
"__nextafterf":"float",
"nexttowardf":"float",
"__nexttowardf":"float",
"remainderf":"float",
"__remainderf":"float",
"scalbnf":"float",
"__scalbnf":"float",
"ilogbf":"int",
"__ilogbf":"int",
"scalblnf":"float",
"__scalblnf":"float",
"nearbyintf":"float",
"__nearbyintf":"float",
"roundf":"float",
"__roundf":"float",
"truncf":"float",
"__truncf":"float",
"remquof":"float",
"__remquof":"float",
"lrintf":"long",
"__lrintf":"long",
"llrintf":"long long",
"__llrintf":"long long",
"lroundf":"long",
"__lroundf":"long",
"llroundf":"long long",
"__llroundf":"long long",
"fdimf":"float",
"__fdimf":"float",
"fmaxf":"float",
"__fmaxf":"float",
"fminf":"float",
"__fminf":"float",
"fmaf":"float",
"__fmaf":"float",
"scalbf":"float",
"__scalbf":"float",
"__fpclassifyl":"int",
"__signbitl":"int",
"__isinfl":"int",
"__finitel":"int",
"__isnanl":"int",
"__iseqsigl":"int",
"__issignalingl":"int",
"acosl":"long double",
"__acosl":"long double",
"asinl":"long double",
"__asinl":"long double",
"atanl":"long double",
"__atanl":"long double",
"atan2l":"long double",
"__atan2l":"long double",
"cosl":"long double",
"__cosl":"long double",
"sinl":"long double",
"__sinl":"long double",
"tanl":"long double",
"__tanl":"long double",
"coshl":"long double",
"__coshl":"long double",
"sinhl":"long double",
"__sinhl":"long double",
"tanhl":"long double",
"__tanhl":"long double",
"acoshl":"long double",
"__acoshl":"long double",
"asinhl":"long double",
"__asinhl":"long double",
"atanhl":"long double",
"__atanhl":"long double",
"expl":"long double",
"__expl":"long double",
"frexpl":"long double",
"__frexpl":"long double",
"ldexpl":"long double",
"__ldexpl":"long double",
"logl":"long double",
"__logl":"long double",
"log10l":"long double",
"__log10l":"long double",
"modfl":"long double",
"__modfl":"long double",
"expm1l":"long double",
"__expm1l":"long double",
"log1pl":"long double",
"__log1pl":"long double",
"logbl":"long double",
"__logbl":"long double",
"exp2l":"long double",
"__exp2l":"long double",
"log2l":"long double",
"__log2l":"long double",
"powl":"long double",
"__powl":"long double",
"sqrtl":"long double",
"__sqrtl":"long double",
"hypotl":"long double",
"__hypotl":"long double",
"cbrtl":"long double",
"__cbrtl":"long double",
"ceill":"long double",
"__ceill":"long double",
"fabsl":"long double",
"__fabsl":"long double",
"floorl":"long double",
"__floorl":"long double",
"fmodl":"long double",
"__fmodl":"long double",
"isinfl":"int",
"finitel":"int",
"dreml":"long double",
"__dreml":"long double",
"significandl":"long double",
"__significandl":"long double",
"copysignl":"long double",
"__copysignl":"long double",
"nanl":"long double",
"__nanl":"long double",
"isnanl":"int",
"j0l":"long double",
"__j0l":"long double",
"j1l":"long double",
"__j1l":"long double",
"jnl":"long double",
"__jnl":"long double",
"y0l":"long double",
"__y0l":"long double",
"y1l":"long double",
"__y1l":"long double",
"ynl":"long double",
"__ynl":"long double",
"erfl":"long double",
"__erfl":"long double",
"erfcl":"long double",
"__erfcl":"long double",
"lgammal":"long double",
"__lgammal":"long double",
"tgammal":"long double",
"__tgammal":"long double",
"gammal":"long double",
"__gammal":"long double",
"lgammal_r":"long double",
"__lgammal_r":"long double",
"rintl":"long double",
"__rintl":"long double",
"nextafterl":"long double",
"__nextafterl":"long double",
"nexttowardl":"long double",
"__nexttowardl":"long double",
"remainderl":"long double",
"__remainderl":"long double",
"scalbnl":"long double",
"__scalbnl":"long double",
"ilogbl":"int",
"__ilogbl":"int",
"scalblnl":"long double",
"__scalblnl":"long double",
"nearbyintl":"long double",
"__nearbyintl":"long double",
"roundl":"long double",
"__roundl":"long double",
"truncl":"long double",
"__truncl":"long double",
"remquol":"long double",
"__remquol":"long double",
"lrintl":"long",
"__lrintl":"long",
"llrintl":"long long",
"__llrintl":"long long",
"lroundl":"long",
"__lroundl":"long",
"llroundl":"long long",
"__llroundl":"long long",
"fdiml":"long double",
"__fdiml":"long double",
"fmaxl":"long double",
"__fmaxl":"long double",
"fminl":"long double",
"__fminl":"long double",
"fmal":"long double",
"__fmal":"long double",
"scalbl":"long double",
"__scalbl":"long double",
"setjmp":"int",
"__sigsetjmp":"int",
"_setjmp":"int",
"longjmp":"void",
"_longjmp":"void",
"siglongjmp":"void",
"__sysv_signal":"__sighandler_t",
"signal":"__sighandler_t",
"kill":"int",
"killpg":"int",
"raise":"int",
"ssignal":"__sighandler_t",
"gsignal":"int",
"psignal":"void",
"psiginfo":"void",
"sigblock":"int",
"sigsetmask":"int",
"siggetmask":"int",
"sigemptyset":"int",
"sigfillset":"int",
"sigaddset":"int",
"sigdelset":"int",
"sigismember":"int",
"sigprocmask":"int",
"sigsuspend":"int",
"sigaction":"int",
"sigpending":"int",
"sigwait":"int",
"sigwaitinfo":"int",
"sigtimedwait":"int",
"sigqueue":"int",
"sigreturn":"int",
"siginterrupt":"int",
"sigaltstack":"int",
"sigstack":"int",
"pthread_sigmask":"int",
"pthread_kill":"int",
"__libc_current_sigrtmin":"int",
"__libc_current_sigrtmax":"int",
"remove":"int",
"rename":"int",
"renameat":"int",
"fclose":"int",
"tmpfile":"FILE *",
"tmpnam":"char *",
"tmpnam_r":"char *",
"tempnam":"char *",
"fflush":"int",
"fflush_unlocked":"int",
"fopen":"FILE *",
"freopen":"FILE *",
"fdopen":"FILE *",
"fmemopen":"FILE *",
"open_memstream":"FILE *",
"setbuf":"void",
"setvbuf":"int",
"setbuffer":"void",
"setlinebuf":"void",
"fprintf":"int",
"printf":"int",
"sprintf":"int",
"vfprintf":"int",
"vprintf":"int",
"vsprintf":"int",
"snprintf":"int",
"vsnprintf":"int",
"vdprintf":"int",
"dprintf":"int",
"fscanf":"int",
"fscanf":"int",
"scanf":"int",
"scanf":"int",
"sscanf":"int",
"sscanf":"int",
"vfscanf":"int",
"vfscanf":"int",
"vscanf":"int",
"vscanf":"int",
"vsscanf":"int",
"vsscanf":"int",
"fgetc":"int",
"getc":"int",
"getchar":"int",
"getc_unlocked":"int",
"getchar_unlocked":"int",
"fgetc_unlocked":"int",
"fputc":"int",
"putc":"int",
"putchar":"int",
"fputc_unlocked":"int",
"putc_unlocked":"int",
"putchar_unlocked":"int",
"getw":"int",
"putw":"int",
"fgets":"char *",
"__getdelim":"__ssize_t",
"getdelim":"__ssize_t",
"getline":"__ssize_t",
"fputs":"int",
"puts":"int",
"ungetc":"int",
"fread":"unsigned long",
"fwrite":"unsigned long",
"fread_unlocked":"size_t",
"fwrite_unlocked":"size_t",
"fseek":"int",
"ftell":"long",
"rewind":"void",
"fseeko":"int",
"ftello":"__off_t",
"fgetpos":"int",
"fsetpos":"int",
"clearerr":"void",
"feof":"int",
"ferror":"int",
"clearerr_unlocked":"void",
"feof_unlocked":"int",
"ferror_unlocked":"int",
"perror":"void",
"fileno":"int",
"fileno_unlocked":"int",
"pclose":"int",
"popen":"FILE *",
"ctermid":"char *",
"flockfile":"void",
"ftrylockfile":"int",
"funlockfile":"void",
"__uflow":"int",
"__overflow":"int",
"__ctype_get_mb_cur_max":"size_t",
"atof":"double",
"atoi":"int",
"atol":"long",
"atoll":"long long",
"strtod":"double",
"strtof":"float",
"strtold":"long double",
"strtol":"long",
"strtoul":"unsigned long",
"strtoq":"long long",
"strtouq":"unsigned long long",
"strtoll":"long long",
"strtoull":"unsigned long long",
"l64a":"char *",
"a64l":"long",
"__bswap_16":"__uint16_t",
"__bswap_32":"__uint32_t",
"__bswap_64":"__uint64_t",
"__uint16_identity":"__uint16_t",
"__uint32_identity":"__uint32_t",
"__uint64_identity":"__uint64_t",
"select":"int",
"pselect":"int",
"random":"long",
"srandom":"void",
"initstate":"char *",
"setstate":"char *",
"random_r":"int",
"srandom_r":"int",
"initstate_r":"int",
"setstate_r":"int",
"rand":"int",
"srand":"void",
"rand_r":"int",
"drand48":"double",
"erand48":"double",
"lrand48":"long",
"nrand48":"long",
"mrand48":"long",
"jrand48":"long",
"srand48":"void",
"seed48":"unsigned short *",
"lcong48":"void",
"drand48_r":"int",
"erand48_r":"int",
"lrand48_r":"int",
"nrand48_r":"int",
"mrand48_r":"int",
"jrand48_r":"int",
"srand48_r":"int",
"seed48_r":"int",
"lcong48_r":"int",
"malloc":"void *",
"calloc":"void *",
"realloc":"void *",
"free":"void",
"reallocarray":"void *",
"reallocarray":"void *",
"alloca":"void *",
"valloc":"void *",
"posix_memalign":"int",
"aligned_alloc":"void *",
"abort":"void",
"atexit":"int",
"at_quick_exit":"int",
"on_exit":"int",
"exit":"void",
"quick_exit":"void",
"_Exit":"void",
"getenv":"char *",
"putenv":"int",
"setenv":"int",
"unsetenv":"int",
"clearenv":"int",
"mktemp":"char *",
"mkstemp":"int",
"mkstemps":"int",
"mkdtemp":"char *",
"system":"int",
"realpath":"char *",
"bsearch":"void *",
"qsort":"void",
"abs":"int",
"labs":"long",
"llabs":"long long",
"div":"div_t",
"ldiv":"ldiv_t",
"lldiv":"lldiv_t",
"ecvt":"char *",
"fcvt":"char *",
"gcvt":"char *",
"qecvt":"char *",
"qfcvt":"char *",
"qgcvt":"char *",
"ecvt_r":"int",
"fcvt_r":"int",
"qecvt_r":"int",
"qfcvt_r":"int",
"mblen":"int",
"mbtowc":"int",
"wctomb":"int",
"mbstowcs":"size_t",
"wcstombs":"size_t",
"rpmatch":"int",
"getsubopt":"int",
"getloadavg":"int",
"memcpy":"void *",
"memmove":"void *",
"memccpy":"void *",
"memset":"void *",
"memcmp":"int",
"__memcmpeq":"int",
"memchr":"void *",
"strcpy":"char *",
"strncpy":"char *",
"strcat":"char *",
"strncat":"char *",
"strcmp":"int",
"strncmp":"int",
"strcoll":"int",
"strxfrm":"unsigned long",
"strcoll_l":"int",
"strxfrm_l":"size_t",
"strdup":"char *",
"strndup":"char *",
"strchr":"char *",
"strrchr":"char *",
"strcspn":"unsigned long",
"strspn":"unsigned long",
"strpbrk":"char *",
"strstr":"char *",
"strtok":"char *",
"__strtok_r":"char *",
"strtok_r":"char *",
"strlen":"unsigned long",
"strnlen":"size_t",
"strerror":"char *",
"strerror_r":"int",
"strerror_l":"char *",
"bcmp":"int",
"bcopy":"void",
"bzero":"void",
"index":"char *",
"rindex":"char *",
"ffs":"int",
"ffsl":"int",
"ffsll":"int",
"strcasecmp":"int",
"strncasecmp":"int",
"strcasecmp_l":"int",
"strncasecmp_l":"int",
"explicit_bzero":"void",
"strsep":"char *",
"strsignal":"char *",
"__stpcpy":"char *",
"stpcpy":"char *",
"__stpncpy":"char *",
"stpncpy":"char *",
"clock":"clock_t",
"time":"time_t",
"difftime":"double",
"mktime":"time_t",
"strftime":"size_t",
"strftime_l":"size_t",
"gmtime":"struct tm *",
"localtime":"struct tm *",
"gmtime_r":"struct tm *",
"localtime_r":"struct tm *",
"asctime":"char *",
"ctime":"char *",
"asctime_r":"char *",
"ctime_r":"char *",
"tzset":"void",
"timegm":"time_t",
"timelocal":"time_t",
"dysize":"int",
"nanosleep":"int",
"clock_getres":"int",
"clock_gettime":"int",
"clock_settime":"int",
"clock_nanosleep":"int",
"clock_getcpuclockid":"int",
"timer_create":"int",
"timer_delete":"int",
"timer_settime":"int",
"timer_gettime":"int",
"timer_getoverrun":"int",
"timespec_get":"int",
"wcscpy":"wchar_t *",
"wcsncpy":"wchar_t *",
"wcscat":"wchar_t *",
"wcsncat":"wchar_t *",
"wcscmp":"int",
"wcsncmp":"int",
"wcscasecmp":"int",
"wcsncasecmp":"int",
"wcscasecmp_l":"int",
"wcsncasecmp_l":"int",
"wcscoll":"int",
"wcsxfrm":"size_t",
"wcscoll_l":"int",
"wcsxfrm_l":"size_t",
"wcsdup":"wchar_t *",
"wcschr":"int *",
"wcsrchr":"wchar_t *",
"wcscspn":"size_t",
"wcsspn":"size_t",
"wcspbrk":"wchar_t *",
"wcsstr":"wchar_t *",
"wcstok":"wchar_t *",
"wcslen":"unsigned long",
"wcsnlen":"size_t",
"wmemchr":"int *",
"wmemcmp":"int",
"wmemcpy":"int *",
"wmemmove":"int *",
"wmemset":"wchar_t *",
"btowc":"wint_t",
"wctob":"int",
"mbsinit":"int",
"mbrtowc":"size_t",
"wcrtomb":"size_t",
"__mbrlen":"size_t",
"mbrlen":"size_t",
"mbsrtowcs":"size_t",
"wcsrtombs":"size_t",
"mbsnrtowcs":"size_t",
"wcsnrtombs":"size_t",
"wcstod":"double",
"wcstof":"float",
"wcstold":"long double",
"wcstol":"long",
"wcstoul":"unsigned long",
"wcstoll":"long long",
"wcstoull":"unsigned long long",
"wcpcpy":"wchar_t *",
"wcpncpy":"wchar_t *",
"open_wmemstream":"__FILE *",
"fwide":"int",
"fwprintf":"int",
"wprintf":"int",
"swprintf":"int",
"vfwprintf":"int",
"vwprintf":"int",
"vswprintf":"int",
"fwscanf":"int",
"fwscanf":"int",
"wscanf":"int",
"wscanf":"int",
"swscanf":"int",
"swscanf":"int",
"vfwscanf":"int",
"vfwscanf":"int",
"vwscanf":"int",
"vwscanf":"int",
"vswscanf":"int",
"vswscanf":"int",
"fgetwc":"wint_t",
"getwc":"wint_t",
"getwchar":"wint_t",
"fputwc":"wint_t",
"putwc":"wint_t",
"putwchar":"wint_t",
"fgetws":"wchar_t *",
"fputws":"int",
"ungetwc":"wint_t",
"wcsftime":"size_t",
"iswalnum":"int",
"iswalpha":"int",
"iswcntrl":"int",
"iswdigit":"int",
"iswgraph":"int",
"iswlower":"int",
"iswprint":"int",
"iswpunct":"int",
"iswspace":"int",
"iswupper":"int",
"iswxdigit":"int",
"iswblank":"int",
"wctype":"wctype_t",
"iswctype":"int",
"towlower":"wint_t",
"towupper":"wint_t",
"wctrans":"wctrans_t",
"towctrans":"wint_t",
"iswalnum_l":"int",
"iswalpha_l":"int",
"iswcntrl_l":"int",
"iswdigit_l":"int",
"iswgraph_l":"int",
"iswlower_l":"int",
"iswprint_l":"int",
"iswpunct_l":"int",
"iswspace_l":"int",
"iswupper_l":"int",
"iswxdigit_l":"int",
"iswblank_l":"int",
"wctype_l":"wctype_t",
"iswctype_l":"int",
"towlower_l":"wint_t",
"towupper_l":"wint_t",
"wctrans_l":"wctrans_t",
"towctrans_l":"wint_t",
"cacos":"void *",
"__cacos":"void *",
"casin":"void *",
"__casin":"void *",
"catan":"void *",
"__catan":"void *",
"ccos":"void *",
"__ccos":"void *",
"csin":"void *",
"__csin":"void *",
"ctan":"void *",
"__ctan":"void *",
"cacosh":"void *",
"__cacosh":"void *",
"casinh":"void *",
"__casinh":"void *",
"catanh":"void *",
"__catanh":"void *",
"ccosh":"void *",
"__ccosh":"void *",
"csinh":"void *",
"__csinh":"void *",
"ctanh":"void *",
"__ctanh":"void *",
"cexp":"void *",
"__cexp":"void *",
"clog":"void *",
"__clog":"void *",
"cpow":"void *",
"__cpow":"void *",
"csqrt":"void *",
"__csqrt":"void *",
"cabs":"void *",
"__cabs":"void *",
"carg":"void *",
"__carg":"void *",
"conj":"void *",
"__conj":"void *",
"cproj":"void *",
"__cproj":"void *",
"cimag":"void *",
"__cimag":"void *",
"creal":"void *",
"__creal":"void *",
"cacosf":"void *",
"__cacosf":"void *",
"casinf":"void *",
"__casinf":"void *",
"catanf":"void *",
"__catanf":"void *",
"ccosf":"void *",
"__ccosf":"void *",
"csinf":"void *",
"__csinf":"void *",
"ctanf":"void *",
"__ctanf":"void *",
"cacoshf":"void *",
"__cacoshf":"void *",
"casinhf":"void *",
"__casinhf":"void *",
"catanhf":"void *",
"__catanhf":"void *",
"ccoshf":"void *",
"__ccoshf":"void *",
"csinhf":"void *",
"__csinhf":"void *",
"ctanhf":"void *",
"__ctanhf":"void *",
"cexpf":"void *",
"__cexpf":"void *",
"clogf":"void *",
"__clogf":"void *",
"cpowf":"void *",
"__cpowf":"void *",
"csqrtf":"void *",
"__csqrtf":"void *",
"cabsf":"void *",
"__cabsf":"void *",
"cargf":"void *",
"__cargf":"void *",
"conjf":"void *",
"__conjf":"void *",
"cprojf":"void *",
"__cprojf":"void *",
"cimagf":"void *",
"__cimagf":"void *",
"crealf":"void *",
"__crealf":"void *",
"cacosl":"void *",
"__cacosl":"void *",
"casinl":"void *",
"__casinl":"void *",
"catanl":"void *",
"__catanl":"void *",
"ccosl":"void *",
"__ccosl":"void *",
"csinl":"void *",
"__csinl":"void *",
"ctanl":"void *",
"__ctanl":"void *",
"cacoshl":"void *",
"__cacoshl":"void *",
"casinhl":"void *",
"__casinhl":"void *",
"catanhl":"void *",
"__catanhl":"void *",
"ccoshl":"void *",
"__ccoshl":"void *",
"csinhl":"void *",
"__csinhl":"void *",
"ctanhl":"void *",
"__ctanhl":"void *",
"cexpl":"void *",
"__cexpl":"void *",
"clogl":"void *",
"__clogl":"void *",
"cpowl":"void *",
"__cpowl":"void *",
"csqrtl":"void *",
"__csqrtl":"void *",
"cabsl":"void *",
"__cabsl":"void *",
"cargl":"void *",
"__cargl":"void *",
"conjl":"void *",
"__conjl":"void *",
"cprojl":"void *",
"__cprojl":"void *",
"cimagl":"void *",
"__cimagl":"void *",
"creall":"void *",
"__creall":"void *",
"feclearexcept":"int",
"fegetexceptflag":"int",
"feraiseexcept":"int",
"fesetexceptflag":"int",
"fetestexcept":"int",
"fegetround":"int",
"fesetround":"int",
"fegetenv":"int",
"feholdexcept":"int",
"fesetenv":"int",
"feupdateenv":"int",
"imaxabs":"intmax_t",
"imaxdiv":"imaxdiv_t",
"strtoimax":"intmax_t",
"strtoumax":"uintmax_t",
"wcstoimax":"intmax_t",
"wcstoumax":"uintmax_t",
"__tg_promote":"_Argument_type_is_not_arithmetic",
"__tg_promote":"double",
"__tg_promote":"double",
"__tg_promote":"double",
"__tg_promote":"double",
"__tg_promote":"double",
"__tg_promote":"double",
"__tg_promote":"float",
"__tg_promote":"double",
"__tg_promote":"long double",
"__tg_promote":"void *",
"__tg_promote":"void *",
"__tg_promote":"void *",
"__tg_acos":"float",
"__tg_acos":"double",
"__tg_acos":"long double",
"__tg_acos":"void *",
"__tg_acos":"void *",
"__tg_acos":"void *",
"__tg_asin":"float",
"__tg_asin":"double",
"__tg_asin":"long double",
"__tg_asin":"void *",
"__tg_asin":"void *",
"__tg_asin":"void *",
"__tg_atan":"float",
"__tg_atan":"double",
"__tg_atan":"long double",
"__tg_atan":"void *",
"__tg_atan":"void *",
"__tg_atan":"void *",
"__tg_acosh":"float",
"__tg_acosh":"double",
"__tg_acosh":"long double",
"__tg_acosh":"void *",
"__tg_acosh":"void *",
"__tg_acosh":"void *",
"__tg_asinh":"float",
"__tg_asinh":"double",
"__tg_asinh":"long double",
"__tg_asinh":"void *",
"__tg_asinh":"void *",
"__tg_asinh":"void *",
"__tg_atanh":"float",
"__tg_atanh":"double",
"__tg_atanh":"long double",
"__tg_atanh":"void *",
"__tg_atanh":"void *",
"__tg_atanh":"void *",
"__tg_cos":"float",
"__tg_cos":"double",
"__tg_cos":"long double",
"__tg_cos":"void *",
"__tg_cos":"void *",
"__tg_cos":"void *",
"__tg_sin":"float",
"__tg_sin":"double",
"__tg_sin":"long double",
"__tg_sin":"void *",
"__tg_sin":"void *",
"__tg_sin":"void *",
"__tg_tan":"float",
"__tg_tan":"double",
"__tg_tan":"long double",
"__tg_tan":"void *",
"__tg_tan":"void *",
"__tg_tan":"void *",
"__tg_cosh":"float",
"__tg_cosh":"double",
"__tg_cosh":"long double",
"__tg_cosh":"void *",
"__tg_cosh":"void *",
"__tg_cosh":"void *",
"__tg_sinh":"float",
"__tg_sinh":"double",
"__tg_sinh":"long double",
"__tg_sinh":"void *",
"__tg_sinh":"void *",
"__tg_sinh":"void *",
"__tg_tanh":"float",
"__tg_tanh":"double",
"__tg_tanh":"long double",
"__tg_tanh":"void *",
"__tg_tanh":"void *",
"__tg_tanh":"void *",
"__tg_exp":"float",
"__tg_exp":"double",
"__tg_exp":"long double",
"__tg_exp":"void *",
"__tg_exp":"void *",
"__tg_exp":"void *",
"__tg_log":"float",
"__tg_log":"double",
"__tg_log":"long double",
"__tg_log":"void *",
"__tg_log":"void *",
"__tg_log":"void *",
"__tg_pow":"float",
"__tg_pow":"double",
"__tg_pow":"long double",
"__tg_pow":"void *",
"__tg_pow":"void *",
"__tg_pow":"void *",
"__tg_sqrt":"float",
"__tg_sqrt":"double",
"__tg_sqrt":"long double",
"__tg_sqrt":"void *",
"__tg_sqrt":"void *",
"__tg_sqrt":"void *",
"__tg_fabs":"float",
"__tg_fabs":"double",
"__tg_fabs":"long double",
"__tg_fabs":"void *",
"__tg_fabs":"void *",
"__tg_fabs":"void *",
"__tg_atan2":"float",
"__tg_atan2":"double",
"__tg_atan2":"long double",
"__tg_cbrt":"float",
"__tg_cbrt":"double",
"__tg_cbrt":"long double",
"__tg_ceil":"float",
"__tg_ceil":"double",
"__tg_ceil":"long double",
"__tg_copysign":"float",
"__tg_copysign":"double",
"__tg_copysign":"long double",
"__tg_erf":"float",
"__tg_erf":"double",
"__tg_erf":"long double",
"__tg_erfc":"float",
"__tg_erfc":"double",
"__tg_erfc":"long double",
"__tg_exp2":"float",
"__tg_exp2":"double",
"__tg_exp2":"long double",
"__tg_expm1":"float",
"__tg_expm1":"double",
"__tg_expm1":"long double",
"__tg_fdim":"float",
"__tg_fdim":"double",
"__tg_fdim":"long double",
"__tg_floor":"float",
"__tg_floor":"double",
"__tg_floor":"long double",
"__tg_fma":"float",
"__tg_fma":"double",
"__tg_fma":"long double",
"__tg_fmax":"float",
"__tg_fmax":"double",
"__tg_fmax":"long double",
"__tg_fmin":"float",
"__tg_fmin":"double",
"__tg_fmin":"long double",
"__tg_fmod":"float",
"__tg_fmod":"double",
"__tg_fmod":"long double",
"__tg_frexp":"float",
"__tg_frexp":"double",
"__tg_frexp":"long double",
"__tg_hypot":"float",
"__tg_hypot":"double",
"__tg_hypot":"long double",
"__tg_ilogb":"int",
"__tg_ilogb":"int",
"__tg_ilogb":"int",
"__tg_ldexp":"float",
"__tg_ldexp":"double",
"__tg_ldexp":"long double",
"__tg_lgamma":"float",
"__tg_lgamma":"double",
"__tg_lgamma":"long double",
"__tg_llrint":"long long",
"__tg_llrint":"long long",
"__tg_llrint":"long long",
"__tg_llround":"long long",
"__tg_llround":"long long",
"__tg_llround":"long long",
"__tg_log10":"float",
"__tg_log10":"double",
"__tg_log10":"long double",
"__tg_log1p":"float",
"__tg_log1p":"double",
"__tg_log1p":"long double",
"__tg_log2":"float",
"__tg_log2":"double",
"__tg_log2":"long double",
"__tg_logb":"float",
"__tg_logb":"double",
"__tg_logb":"long double",
"__tg_lrint":"long",
"__tg_lrint":"long",
"__tg_lrint":"long",
"__tg_lround":"long",
"__tg_lround":"long",
"__tg_lround":"long",
"__tg_nearbyint":"float",
"__tg_nearbyint":"double",
"__tg_nearbyint":"long double",
"__tg_nextafter":"float",
"__tg_nextafter":"double",
"__tg_nextafter":"long double",
"__tg_nexttoward":"float",
"__tg_nexttoward":"double",
"__tg_nexttoward":"long double",
"__tg_remainder":"float",
"__tg_remainder":"double",
"__tg_remainder":"long double",
"__tg_remquo":"float",
"__tg_remquo":"double",
"__tg_remquo":"long double",
"__tg_rint":"float",
"__tg_rint":"double",
"__tg_rint":"long double",
"__tg_round":"float",
"__tg_round":"double",
"__tg_round":"long double",
"__tg_scalbn":"float",
"__tg_scalbn":"double",
"__tg_scalbn":"long double",
"__tg_scalbln":"float",
"__tg_scalbln":"double",
"__tg_scalbln":"long double",
"__tg_tgamma":"float",
"__tg_tgamma":"double",
"__tg_tgamma":"long double",
"__tg_trunc":"float",
"__tg_trunc":"double",
"__tg_trunc":"long double",
"__tg_carg":"float",
"__tg_carg":"double",
"__tg_carg":"long double",
"__tg_carg":"void *",
"__tg_carg":"void *",
"__tg_carg":"void *",
"__tg_cimag":"float",
"__tg_cimag":"double",
"__tg_cimag":"long double",
"__tg_cimag":"void *",
"__tg_cimag":"void *",
"__tg_cimag":"void *",
"__tg_conj":"void *",
"__tg_conj":"void *",
"__tg_conj":"void *",
"__tg_conj":"void *",
"__tg_conj":"void *",
"__tg_conj":"void *",
"__tg_cproj":"void *",
"__tg_cproj":"void *",
"__tg_cproj":"void *",
"__tg_cproj":"void *",
"__tg_cproj":"void *",
"__tg_cproj":"void *",
"__tg_creal":"float",
"__tg_creal":"double",
"__tg_creal":"long double",
"__tg_creal":"void *",
"__tg_creal":"void *",
"__tg_creal":"void *",
"mbrtoc16":"size_t",
"c16rtomb":"size_t",
"mbrtoc32":"size_t",
"c32rtomb":"size_t",
"access":"int",
"faccessat":"int",
"lseek":"__off_t",
"close":"int",
"closefrom":"void",
"read":"ssize_t",
"write":"ssize_t",
"pread":"ssize_t",
"pwrite":"ssize_t",
"pipe":"int",
"alarm":"unsigned int",
"sleep":"unsigned int",
"ualarm":"__useconds_t",
"usleep":"int",
"pause":"int",
"chown":"int",
"fchown":"int",
"lchown":"int",
"fchownat":"int",
"chdir":"int",
"fchdir":"int",
"getcwd":"char *",
"getwd":"char *",
"dup":"int",
"dup2":"int",
"execve":"int",
"fexecve":"int",
"execv":"int",
"execle":"int",
"execl":"int",
"execvp":"int",
"execlp":"int",
"nice":"int",
"_exit":"void",
"pathconf":"long",
"fpathconf":"long",
"sysconf":"long",
"confstr":"size_t",
"getpid":"__pid_t",
"getppid":"__pid_t",
"getpgrp":"__pid_t",
"__getpgid":"__pid_t",
"getpgid":"__pid_t",
"setpgid":"int",
"setpgrp":"int",
"setsid":"__pid_t",
"getsid":"__pid_t",
"getuid":"__uid_t",
"geteuid":"__uid_t",
"getgid":"__gid_t",
"getegid":"__gid_t",
"getgroups":"int",
"setuid":"int",
"setreuid":"int",
"seteuid":"int",
"setgid":"int",
"setregid":"int",
"setegid":"int",
"fork":"__pid_t",
"vfork":"int",
"ttyname":"char *",
"ttyname_r":"int",
"isatty":"int",
"ttyslot":"int",
"link":"int",
"linkat":"int",
"symlink":"int",
"readlink":"ssize_t",
"symlinkat":"int",
"readlinkat":"ssize_t",
"unlink":"int",
"unlinkat":"int",
"rmdir":"int",
"tcgetpgrp":"__pid_t",
"tcsetpgrp":"int",
"getlogin":"char *",
"getlogin_r":"int",
"setlogin":"int",
"getopt":"int",
"gethostname":"int",
"sethostname":"int",
"sethostid":"int",
"getdomainname":"int",
"setdomainname":"int",
"vhangup":"int",
"revoke":"int",
"profil":"int",
"acct":"int",
"getusershell":"char *",
"endusershell":"void",
"setusershell":"void",
"daemon":"int",
"chroot":"int",
"getpass":"char *",
"fsync":"int",
"gethostid":"long",
"sync":"void",
"getpagesize":"int",
"getdtablesize":"int",
"truncate":"int",
"ftruncate":"int",
"brk":"int",
"sbrk":"void *",
"syscall":"long",
"lockf":"int",
"fdatasync":"int",
"crypt":"char *",
"getentropy":"int",
"stat":"int",
"fstat":"int",
"fstatat":"int",
"lstat":"int",
"chmod":"int",
"lchmod":"int",
"fchmod":"int",
"fchmodat":"int",
"umask":"__mode_t",
"mkdir":"int",
"mkdirat":"int",
"mknod":"int",
"mknodat":"int",
"mkfifo":"int",
"mkfifoat":"int",
"utimensat":"int",
"futimens":"int",

  }

