
class dict:
  dictionary={

"__assert_fail":"void",
"__assert_perror_fail":"void",
"__assert":"void",
"__ctype_b_loc":"const unsigned short **",
"__ctype_tolower_loc":"const __int32_t **",
"__ctype_toupper_loc":"const __int32_t **",
"isalnum":"int",
"isalpha":"int",
"iscntrl":"int",
"isdigit":"int",
"islower":"int",
"isgraph":"int",
"isprint":"int",
"ispunct":"int",
"isspace":"int",
"isupper":"int",
"isxdigit":"int",
"tolower":"int",
"toupper":"int",
"isblank":"int",
"isctype":"int",
"isascii":"int",
"toascii":"int",
"_toupper":"int",
"_tolower":"int",
"isalnum_l":"int",
"isalpha_l":"int",
"iscntrl_l":"int",
"isdigit_l":"int",
"islower_l":"int",
"isgraph_l":"int",
"isprint_l":"int",
"ispunct_l":"int",
"isspace_l":"int",
"isupper_l":"int",
"isxdigit_l":"int",
"isblank_l":"int",
"__tolower_l":"int",
"tolower_l":"int",
"__toupper_l":"int",
"toupper_l":"int",
"__errno_location":"int *",
"__sysconf":"long",
"setlocale":"char *",
"localeconv":"struct lconv *",
"newlocale":"locale_t",
"duplocale":"locale_t",
"freelocale":"void",
"uselocale":"locale_t",
"__is_null_pointer":"bool",
"__fpclassify":"int",
"__signbit":"int",
"__isinf":"int",
"__finite":"int",
"__isnan":"int",
"__iseqsig":"int",
"__issignaling":"int",
"acos":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__acos":"double",
"asin":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__asin":"double",
"atan":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__atan":"double",
"atan2":[("double","(double, double)"),("float","(float, float)"),("long double","(long double, long double)")],
"__atan2":"double",
"cos":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__cos":"double",
"sin":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__sin":"double",
"tan":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__tan":"double",
"cosh":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__cosh":"double",
"sinh":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__sinh":"double",
"tanh":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__tanh":"double",
"sincos":"void",
"__sincos":"void",
"acosh":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__acosh":"double",
"asinh":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__asinh":"double",
"atanh":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__atanh":"double",
"exp":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__exp":"double",
"frexp":[("double","(double, int *)"),("float","(float, int *)"),("long double","(long double, int *)")],
"__frexp":"double",
"ldexp":[("double","(double, int)"),("float","(float, int)"),("long double","(long double, int)")],
"__ldexp":"double",
"log":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__log":"double",
"log10":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__log10":"double",
"modf":[("double","(double, double *)"),("float","(float, float *)"),("long double","(long double, long double *)")],
"__modf":"double",
"exp10":"double",
"__exp10":"double",
"expm1":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__expm1":"double",
"log1p":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__log1p":"double",
"logb":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__logb":"double",
"exp2":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__exp2":"double",
"log2":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__log2":"double",
"pow":[("double","(double, double)"),("float","(float, float)"),("long double","(long double, long double)")],
"__pow":"double",
"sqrt":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__sqrt":"double",
"hypot":[("double","(double, double)"),("float","(float, float)"),("long double","(long double, long double)")],
"__hypot":"double",
"cbrt":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__cbrt":"double",
"ceil":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__ceil":"double",
"fabs":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__fabs":"double",
"floor":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__floor":"double",
"fmod":[("double","(double, double)"),("float","(float, float)"),("long double","(long double, long double)")],
"__fmod":"double",
"finite":"int",
"drem":"double",
"__drem":"double",
"significand":"double",
"__significand":"double",
"copysign":[("double","(double, double)"),("float","(float, float)"),("long double","(long double, long double)")],
"__copysign":"double",
"nan":"double",
"__nan":"double",
"j0":"double",
"__j0":"double",
"j1":"double",
"__j1":"double",
"jn":"double",
"__jn":"double",
"y0":"double",
"__y0":"double",
"y1":"double",
"__y1":"double",
"yn":"double",
"__yn":"double",
"erf":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__erf":"double",
"erfc":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__erfc":"double",
"lgamma":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__lgamma":"double",
"tgamma":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__tgamma":"double",
"gamma":"double",
"__gamma":"double",
"lgamma_r":"double",
"__lgamma_r":"double",
"rint":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__rint":"double",
"nextafter":[("double","(double, double)"),("float","(float, float)"),("long double","(long double, long double)")],
"__nextafter":"double",
"nexttoward":[("double","(double, long double)"),("float","(float, long double)"),("long double","(long double, long double)")],
"__nexttoward":"double",
"nextdown":"double",
"__nextdown":"double",
"nextup":"double",
"__nextup":"double",
"remainder":[("double","(double, double)"),("float","(float, float)"),("long double","(long double, long double)")],
"__remainder":"double",
"scalbn":[("double","(double, int)"),("float","(float, int)"),("long double","(long double, int)")],
"__scalbn":"double",
"ilogb":[("int","(double)"),("int","(float)"),("int","(long double)")],
"__ilogb":"int",
"llogb":"long",
"__llogb":"long",
"scalbln":[("double","(double, long)"),("float","(float, long)"),("long double","(long double, long)")],
"__scalbln":"double",
"nearbyint":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__nearbyint":"double",
"round":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__round":"double",
"trunc":[("double","(double)"),("float","(float)"),("long double","(long double)")],
"__trunc":"double",
"remquo":[("double","(double, double, int *)"),("float","(float, float, int *)"),("long double","(long double, long double, int *)")],
"__remquo":"double",
"lrint":[("long","(double)"),("long","(float)"),("long","(long double)")],
"__lrint":"long",
"llrint":[("long long","(double)"),("long long","(float)"),("long long","(long double)")],
"__llrint":"long long",
"lround":[("long","(double)"),("long","(float)"),("long","(long double)")],
"__lround":"long",
"llround":[("long long","(double)"),("long long","(float)"),("long long","(long double)")],
"__llround":"long long",
"fdim":[("double","(double, double)"),("float","(float, float)"),("long double","(long double, long double)")],
"__fdim":"double",
"fmax":[("double","(double, double)"),("float","(float, float)"),("long double","(long double, long double)")],
"__fmax":"double",
"fmin":[("double","(double, double)"),("float","(float, float)"),("long double","(long double, long double)")],
"__fmin":"double",
"fma":[("double","(double, double, double)"),("float","(float, float, float)"),("long double","(long double, long double, long double)")],
"__fma":"double",
"roundeven":"double",
"__roundeven":"double",
"fromfp":"__intmax_t",
"__fromfp":"__intmax_t",
"ufromfp":"__uintmax_t",
"__ufromfp":"__uintmax_t",
"fromfpx":"__intmax_t",
"__fromfpx":"__intmax_t",
"ufromfpx":"__uintmax_t",
"__ufromfpx":"__uintmax_t",
"canonicalize":"int",
"fmaxmag":"double",
"__fmaxmag":"double",
"fminmag":"double",
"__fminmag":"double",
"fmaximum":"double",
"__fmaximum":"double",
"fminimum":"double",
"__fminimum":"double",
"fmaximum_num":"double",
"__fmaximum_num":"double",
"fminimum_num":"double",
"__fminimum_num":"double",
"fmaximum_mag":"double",
"__fmaximum_mag":"double",
"fminimum_mag":"double",
"__fminimum_mag":"double",
"fmaximum_mag_num":"double",
"__fmaximum_mag_num":"double",
"fminimum_mag_num":"double",
"__fminimum_mag_num":"double",
"totalorder":"int",
"totalordermag":"int",
"getpayload":"double",
"__getpayload":"double",
"setpayload":"int",
"setpayloadsig":"int",
"scalb":"double",
"__scalb":"double",
"__fpclassifyf":"int",
"__signbitf":"int",
"__isinff":"int",
"__finitef":"int",
"__isnanf":"int",
"__iseqsigf":"int",
"__issignalingf":"int",
"acosf":"float",
"__acosf":"float",
"asinf":"float",
"__asinf":"float",
"atanf":"float",
"__atanf":"float",
"atan2f":"float",
"__atan2f":"float",
"cosf":"float",
"__cosf":"float",
"sinf":"float",
"__sinf":"float",
"tanf":"float",
"__tanf":"float",
"coshf":"float",
"__coshf":"float",
"sinhf":"float",
"__sinhf":"float",
"tanhf":"float",
"__tanhf":"float",
"sincosf":"void",
"__sincosf":"void",
"acoshf":"float",
"__acoshf":"float",
"asinhf":"float",
"__asinhf":"float",
"atanhf":"float",
"__atanhf":"float",
"expf":"float",
"__expf":"float",
"frexpf":"float",
"__frexpf":"float",
"ldexpf":"float",
"__ldexpf":"float",
"logf":"float",
"__logf":"float",
"log10f":"float",
"__log10f":"float",
"modff":"float",
"__modff":"float",
"exp10f":"float",
"__exp10f":"float",
"expm1f":"float",
"__expm1f":"float",
"log1pf":"float",
"__log1pf":"float",
"logbf":"float",
"__logbf":"float",
"exp2f":"float",
"__exp2f":"float",
"log2f":"float",
"__log2f":"float",
"powf":"float",
"__powf":"float",
"sqrtf":"float",
"__sqrtf":"float",
"hypotf":"float",
"__hypotf":"float",
"cbrtf":"float",
"__cbrtf":"float",
"ceilf":"float",
"__ceilf":"float",
"fabsf":"float",
"__fabsf":"float",
"floorf":"float",
"__floorf":"float",
"fmodf":"float",
"__fmodf":"float",
"isinff":"int",
"finitef":"int",
"dremf":"float",
"__dremf":"float",
"significandf":"float",
"__significandf":"float",
"copysignf":"float",
"__copysignf":"float",
"nanf":"float",
"__nanf":"float",
"isnanf":"int",
"j0f":"float",
"__j0f":"float",
"j1f":"float",
"__j1f":"float",
"jnf":"float",
"__jnf":"float",
"y0f":"float",
"__y0f":"float",
"y1f":"float",
"__y1f":"float",
"ynf":"float",
"__ynf":"float",
"erff":"float",
"__erff":"float",
"erfcf":"float",
"__erfcf":"float",
"lgammaf":"float",
"__lgammaf":"float",
"tgammaf":"float",
"__tgammaf":"float",
"gammaf":"float",
"__gammaf":"float",
"lgammaf_r":"float",
"__lgammaf_r":"float",
"rintf":"float",
"__rintf":"float",
"nextafterf":"float",
"__nextafterf":"float",
"nexttowardf":"float",
"__nexttowardf":"float",
"nextdownf":"float",
"__nextdownf":"float",
"nextupf":"float",
"__nextupf":"float",
"remainderf":"float",
"__remainderf":"float",
"scalbnf":"float",
"__scalbnf":"float",
"ilogbf":"int",
"__ilogbf":"int",
"llogbf":"long",
"__llogbf":"long",
"scalblnf":"float",
"__scalblnf":"float",
"nearbyintf":"float",
"__nearbyintf":"float",
"roundf":"float",
"__roundf":"float",
"truncf":"float",
"__truncf":"float",
"remquof":"float",
"__remquof":"float",
"lrintf":"long",
"__lrintf":"long",
"llrintf":"long long",
"__llrintf":"long long",
"lroundf":"long",
"__lroundf":"long",
"llroundf":"long long",
"__llroundf":"long long",
"fdimf":"float",
"__fdimf":"float",
"fmaxf":"float",
"__fmaxf":"float",
"fminf":"float",
"__fminf":"float",
"fmaf":"float",
"__fmaf":"float",
"roundevenf":"float",
"__roundevenf":"float",
"fromfpf":"__intmax_t",
"__fromfpf":"__intmax_t",
"ufromfpf":"__uintmax_t",
"__ufromfpf":"__uintmax_t",
"fromfpxf":"__intmax_t",
"__fromfpxf":"__intmax_t",
"ufromfpxf":"__uintmax_t",
"__ufromfpxf":"__uintmax_t",
"canonicalizef":"int",
"fmaxmagf":"float",
"__fmaxmagf":"float",
"fminmagf":"float",
"__fminmagf":"float",
"fmaximumf":"float",
"__fmaximumf":"float",
"fminimumf":"float",
"__fminimumf":"float",
"fmaximum_numf":"float",
"__fmaximum_numf":"float",
"fminimum_numf":"float",
"__fminimum_numf":"float",
"fmaximum_magf":"float",
"__fmaximum_magf":"float",
"fminimum_magf":"float",
"__fminimum_magf":"float",
"fmaximum_mag_numf":"float",
"__fmaximum_mag_numf":"float",
"fminimum_mag_numf":"float",
"__fminimum_mag_numf":"float",
"totalorderf":"int",
"totalordermagf":"int",
"getpayloadf":"float",
"__getpayloadf":"float",
"setpayloadf":"int",
"setpayloadsigf":"int",
"scalbf":"float",
"__scalbf":"float",
"__fpclassifyl":"int",
"__signbitl":"int",
"__isinfl":"int",
"__finitel":"int",
"__isnanl":"int",
"__iseqsigl":"int",
"__issignalingl":"int",
"acosl":"long double",
"__acosl":"long double",
"asinl":"long double",
"__asinl":"long double",
"atanl":"long double",
"__atanl":"long double",
"atan2l":"long double",
"__atan2l":"long double",
"cosl":"long double",
"__cosl":"long double",
"sinl":"long double",
"__sinl":"long double",
"tanl":"long double",
"__tanl":"long double",
"coshl":"long double",
"__coshl":"long double",
"sinhl":"long double",
"__sinhl":"long double",
"tanhl":"long double",
"__tanhl":"long double",
"sincosl":"void",
"__sincosl":"void",
"acoshl":"long double",
"__acoshl":"long double",
"asinhl":"long double",
"__asinhl":"long double",
"atanhl":"long double",
"__atanhl":"long double",
"expl":"long double",
"__expl":"long double",
"frexpl":"long double",
"__frexpl":"long double",
"ldexpl":"long double",
"__ldexpl":"long double",
"logl":"long double",
"__logl":"long double",
"log10l":"long double",
"__log10l":"long double",
"modfl":"long double",
"__modfl":"long double",
"exp10l":"long double",
"__exp10l":"long double",
"expm1l":"long double",
"__expm1l":"long double",
"log1pl":"long double",
"__log1pl":"long double",
"logbl":"long double",
"__logbl":"long double",
"exp2l":"long double",
"__exp2l":"long double",
"log2l":"long double",
"__log2l":"long double",
"powl":"long double",
"__powl":"long double",
"sqrtl":"long double",
"__sqrtl":"long double",
"hypotl":"long double",
"__hypotl":"long double",
"cbrtl":"long double",
"__cbrtl":"long double",
"ceill":"long double",
"__ceill":"long double",
"fabsl":"long double",
"__fabsl":"long double",
"floorl":"long double",
"__floorl":"long double",
"fmodl":"long double",
"__fmodl":"long double",
"isinfl":"int",
"finitel":"int",
"dreml":"long double",
"__dreml":"long double",
"significandl":"long double",
"__significandl":"long double",
"copysignl":"long double",
"__copysignl":"long double",
"nanl":"long double",
"__nanl":"long double",
"isnanl":"int",
"j0l":"long double",
"__j0l":"long double",
"j1l":"long double",
"__j1l":"long double",
"jnl":"long double",
"__jnl":"long double",
"y0l":"long double",
"__y0l":"long double",
"y1l":"long double",
"__y1l":"long double",
"ynl":"long double",
"__ynl":"long double",
"erfl":"long double",
"__erfl":"long double",
"erfcl":"long double",
"__erfcl":"long double",
"lgammal":"long double",
"__lgammal":"long double",
"tgammal":"long double",
"__tgammal":"long double",
"gammal":"long double",
"__gammal":"long double",
"lgammal_r":"long double",
"__lgammal_r":"long double",
"rintl":"long double",
"__rintl":"long double",
"nextafterl":"long double",
"__nextafterl":"long double",
"nexttowardl":"long double",
"__nexttowardl":"long double",
"nextdownl":"long double",
"__nextdownl":"long double",
"nextupl":"long double",
"__nextupl":"long double",
"remainderl":"long double",
"__remainderl":"long double",
"scalbnl":"long double",
"__scalbnl":"long double",
"ilogbl":"int",
"__ilogbl":"int",
"llogbl":"long",
"__llogbl":"long",
"scalblnl":"long double",
"__scalblnl":"long double",
"nearbyintl":"long double",
"__nearbyintl":"long double",
"roundl":"long double",
"__roundl":"long double",
"truncl":"long double",
"__truncl":"long double",
"remquol":"long double",
"__remquol":"long double",
"lrintl":"long",
"__lrintl":"long",
"llrintl":"long long",
"__llrintl":"long long",
"lroundl":"long",
"__lroundl":"long",
"llroundl":"long long",
"__llroundl":"long long",
"fdiml":"long double",
"__fdiml":"long double",
"fmaxl":"long double",
"__fmaxl":"long double",
"fminl":"long double",
"__fminl":"long double",
"fmal":"long double",
"__fmal":"long double",
"roundevenl":"long double",
"__roundevenl":"long double",
"fromfpl":"__intmax_t",
"__fromfpl":"__intmax_t",
"ufromfpl":"__uintmax_t",
"__ufromfpl":"__uintmax_t",
"fromfpxl":"__intmax_t",
"__fromfpxl":"__intmax_t",
"ufromfpxl":"__uintmax_t",
"__ufromfpxl":"__uintmax_t",
"canonicalizel":"int",
"fmaxmagl":"long double",
"__fmaxmagl":"long double",
"fminmagl":"long double",
"__fminmagl":"long double",
"fmaximuml":"long double",
"__fmaximuml":"long double",
"fminimuml":"long double",
"__fminimuml":"long double",
"fmaximum_numl":"long double",
"__fmaximum_numl":"long double",
"fminimum_numl":"long double",
"__fminimum_numl":"long double",
"fmaximum_magl":"long double",
"__fmaximum_magl":"long double",
"fminimum_magl":"long double",
"__fminimum_magl":"long double",
"fmaximum_mag_numl":"long double",
"__fmaximum_mag_numl":"long double",
"fminimum_mag_numl":"long double",
"__fminimum_mag_numl":"long double",
"totalorderl":"int",
"totalordermagl":"int",
"getpayloadl":"long double",
"__getpayloadl":"long double",
"setpayloadl":"int",
"setpayloadsigl":"int",
"scalbl":"long double",
"__scalbl":"long double",
"acosf32":"_Float32",
"__acosf32":"_Float32",
"asinf32":"_Float32",
"__asinf32":"_Float32",
"atanf32":"_Float32",
"__atanf32":"_Float32",
"atan2f32":"_Float32",
"__atan2f32":"_Float32",
"cosf32":"_Float32",
"__cosf32":"_Float32",
"sinf32":"_Float32",
"__sinf32":"_Float32",
"tanf32":"_Float32",
"__tanf32":"_Float32",
"coshf32":"_Float32",
"__coshf32":"_Float32",
"sinhf32":"_Float32",
"__sinhf32":"_Float32",
"tanhf32":"_Float32",
"__tanhf32":"_Float32",
"sincosf32":"void",
"__sincosf32":"void",
"acoshf32":"_Float32",
"__acoshf32":"_Float32",
"asinhf32":"_Float32",
"__asinhf32":"_Float32",
"atanhf32":"_Float32",
"__atanhf32":"_Float32",
"expf32":"_Float32",
"__expf32":"_Float32",
"frexpf32":"_Float32",
"__frexpf32":"_Float32",
"ldexpf32":"_Float32",
"__ldexpf32":"_Float32",
"logf32":"_Float32",
"__logf32":"_Float32",
"log10f32":"_Float32",
"__log10f32":"_Float32",
"modff32":"_Float32",
"__modff32":"_Float32",
"exp10f32":"_Float32",
"__exp10f32":"_Float32",
"expm1f32":"_Float32",
"__expm1f32":"_Float32",
"log1pf32":"_Float32",
"__log1pf32":"_Float32",
"logbf32":"_Float32",
"__logbf32":"_Float32",
"exp2f32":"_Float32",
"__exp2f32":"_Float32",
"log2f32":"_Float32",
"__log2f32":"_Float32",
"powf32":"_Float32",
"__powf32":"_Float32",
"sqrtf32":"_Float32",
"__sqrtf32":"_Float32",
"hypotf32":"_Float32",
"__hypotf32":"_Float32",
"cbrtf32":"_Float32",
"__cbrtf32":"_Float32",
"ceilf32":"_Float32",
"__ceilf32":"_Float32",
"fabsf32":"_Float32",
"__fabsf32":"_Float32",
"floorf32":"_Float32",
"__floorf32":"_Float32",
"fmodf32":"_Float32",
"__fmodf32":"_Float32",
"copysignf32":"_Float32",
"__copysignf32":"_Float32",
"nanf32":"_Float32",
"__nanf32":"_Float32",
"j0f32":"_Float32",
"__j0f32":"_Float32",
"j1f32":"_Float32",
"__j1f32":"_Float32",
"jnf32":"_Float32",
"__jnf32":"_Float32",
"y0f32":"_Float32",
"__y0f32":"_Float32",
"y1f32":"_Float32",
"__y1f32":"_Float32",
"ynf32":"_Float32",
"__ynf32":"_Float32",
"erff32":"_Float32",
"__erff32":"_Float32",
"erfcf32":"_Float32",
"__erfcf32":"_Float32",
"lgammaf32":"_Float32",
"__lgammaf32":"_Float32",
"tgammaf32":"_Float32",
"__tgammaf32":"_Float32",
"lgammaf32_r":"_Float32",
"__lgammaf32_r":"_Float32",
"rintf32":"_Float32",
"__rintf32":"_Float32",
"nextafterf32":"_Float32",
"__nextafterf32":"_Float32",
"nextdownf32":"_Float32",
"__nextdownf32":"_Float32",
"nextupf32":"_Float32",
"__nextupf32":"_Float32",
"remainderf32":"_Float32",
"__remainderf32":"_Float32",
"scalbnf32":"_Float32",
"__scalbnf32":"_Float32",
"ilogbf32":"int",
"__ilogbf32":"int",
"llogbf32":"long",
"__llogbf32":"long",
"scalblnf32":"_Float32",
"__scalblnf32":"_Float32",
"nearbyintf32":"_Float32",
"__nearbyintf32":"_Float32",
"roundf32":"_Float32",
"__roundf32":"_Float32",
"truncf32":"_Float32",
"__truncf32":"_Float32",
"remquof32":"_Float32",
"__remquof32":"_Float32",
"lrintf32":"long",
"__lrintf32":"long",
"llrintf32":"long long",
"__llrintf32":"long long",
"lroundf32":"long",
"__lroundf32":"long",
"llroundf32":"long long",
"__llroundf32":"long long",
"fdimf32":"_Float32",
"__fdimf32":"_Float32",
"fmaxf32":"_Float32",
"__fmaxf32":"_Float32",
"fminf32":"_Float32",
"__fminf32":"_Float32",
"fmaf32":"_Float32",
"__fmaf32":"_Float32",
"roundevenf32":"_Float32",
"__roundevenf32":"_Float32",
"fromfpf32":"__intmax_t",
"__fromfpf32":"__intmax_t",
"ufromfpf32":"__uintmax_t",
"__ufromfpf32":"__uintmax_t",
"fromfpxf32":"__intmax_t",
"__fromfpxf32":"__intmax_t",
"ufromfpxf32":"__uintmax_t",
"__ufromfpxf32":"__uintmax_t",
"canonicalizef32":"int",
"fmaxmagf32":"_Float32",
"__fmaxmagf32":"_Float32",
"fminmagf32":"_Float32",
"__fminmagf32":"_Float32",
"fmaximumf32":"_Float32",
"__fmaximumf32":"_Float32",
"fminimumf32":"_Float32",
"__fminimumf32":"_Float32",
"fmaximum_numf32":"_Float32",
"__fmaximum_numf32":"_Float32",
"fminimum_numf32":"_Float32",
"__fminimum_numf32":"_Float32",
"fmaximum_magf32":"_Float32",
"__fmaximum_magf32":"_Float32",
"fminimum_magf32":"_Float32",
"__fminimum_magf32":"_Float32",
"fmaximum_mag_numf32":"_Float32",
"__fmaximum_mag_numf32":"_Float32",
"fminimum_mag_numf32":"_Float32",
"__fminimum_mag_numf32":"_Float32",
"totalorderf32":"int",
"totalordermagf32":"int",
"getpayloadf32":"_Float32",
"__getpayloadf32":"_Float32",
"setpayloadf32":"int",
"setpayloadsigf32":"int",
"acosf64":"_Float64",
"__acosf64":"_Float64",
"asinf64":"_Float64",
"__asinf64":"_Float64",
"atanf64":"_Float64",
"__atanf64":"_Float64",
"atan2f64":"_Float64",
"__atan2f64":"_Float64",
"cosf64":"_Float64",
"__cosf64":"_Float64",
"sinf64":"_Float64",
"__sinf64":"_Float64",
"tanf64":"_Float64",
"__tanf64":"_Float64",
"coshf64":"_Float64",
"__coshf64":"_Float64",
"sinhf64":"_Float64",
"__sinhf64":"_Float64",
"tanhf64":"_Float64",
"__tanhf64":"_Float64",
"sincosf64":"void",
"__sincosf64":"void",
"acoshf64":"_Float64",
"__acoshf64":"_Float64",
"asinhf64":"_Float64",
"__asinhf64":"_Float64",
"atanhf64":"_Float64",
"__atanhf64":"_Float64",
"expf64":"_Float64",
"__expf64":"_Float64",
"frexpf64":"_Float64",
"__frexpf64":"_Float64",
"ldexpf64":"_Float64",
"__ldexpf64":"_Float64",
"logf64":"_Float64",
"__logf64":"_Float64",
"log10f64":"_Float64",
"__log10f64":"_Float64",
"modff64":"_Float64",
"__modff64":"_Float64",
"exp10f64":"_Float64",
"__exp10f64":"_Float64",
"expm1f64":"_Float64",
"__expm1f64":"_Float64",
"log1pf64":"_Float64",
"__log1pf64":"_Float64",
"logbf64":"_Float64",
"__logbf64":"_Float64",
"exp2f64":"_Float64",
"__exp2f64":"_Float64",
"log2f64":"_Float64",
"__log2f64":"_Float64",
"powf64":"_Float64",
"__powf64":"_Float64",
"sqrtf64":"_Float64",
"__sqrtf64":"_Float64",
"hypotf64":"_Float64",
"__hypotf64":"_Float64",
"cbrtf64":"_Float64",
"__cbrtf64":"_Float64",
"ceilf64":"_Float64",
"__ceilf64":"_Float64",
"fabsf64":"_Float64",
"__fabsf64":"_Float64",
"floorf64":"_Float64",
"__floorf64":"_Float64",
"fmodf64":"_Float64",
"__fmodf64":"_Float64",
"copysignf64":"_Float64",
"__copysignf64":"_Float64",
"nanf64":"_Float64",
"__nanf64":"_Float64",
"j0f64":"_Float64",
"__j0f64":"_Float64",
"j1f64":"_Float64",
"__j1f64":"_Float64",
"jnf64":"_Float64",
"__jnf64":"_Float64",
"y0f64":"_Float64",
"__y0f64":"_Float64",
"y1f64":"_Float64",
"__y1f64":"_Float64",
"ynf64":"_Float64",
"__ynf64":"_Float64",
"erff64":"_Float64",
"__erff64":"_Float64",
"erfcf64":"_Float64",
"__erfcf64":"_Float64",
"lgammaf64":"_Float64",
"__lgammaf64":"_Float64",
"tgammaf64":"_Float64",
"__tgammaf64":"_Float64",
"lgammaf64_r":"_Float64",
"__lgammaf64_r":"_Float64",
"rintf64":"_Float64",
"__rintf64":"_Float64",
"nextafterf64":"_Float64",
"__nextafterf64":"_Float64",
"nextdownf64":"_Float64",
"__nextdownf64":"_Float64",
"nextupf64":"_Float64",
"__nextupf64":"_Float64",
"remainderf64":"_Float64",
"__remainderf64":"_Float64",
"scalbnf64":"_Float64",
"__scalbnf64":"_Float64",
"ilogbf64":"int",
"__ilogbf64":"int",
"llogbf64":"long",
"__llogbf64":"long",
"scalblnf64":"_Float64",
"__scalblnf64":"_Float64",
"nearbyintf64":"_Float64",
"__nearbyintf64":"_Float64",
"roundf64":"_Float64",
"__roundf64":"_Float64",
"truncf64":"_Float64",
"__truncf64":"_Float64",
"remquof64":"_Float64",
"__remquof64":"_Float64",
"lrintf64":"long",
"__lrintf64":"long",
"llrintf64":"long long",
"__llrintf64":"long long",
"lroundf64":"long",
"__lroundf64":"long",
"llroundf64":"long long",
"__llroundf64":"long long",
"fdimf64":"_Float64",
"__fdimf64":"_Float64",
"fmaxf64":"_Float64",
"__fmaxf64":"_Float64",
"fminf64":"_Float64",
"__fminf64":"_Float64",
"fmaf64":"_Float64",
"__fmaf64":"_Float64",
"roundevenf64":"_Float64",
"__roundevenf64":"_Float64",
"fromfpf64":"__intmax_t",
"__fromfpf64":"__intmax_t",
"ufromfpf64":"__uintmax_t",
"__ufromfpf64":"__uintmax_t",
"fromfpxf64":"__intmax_t",
"__fromfpxf64":"__intmax_t",
"ufromfpxf64":"__uintmax_t",
"__ufromfpxf64":"__uintmax_t",
"canonicalizef64":"int",
"fmaxmagf64":"_Float64",
"__fmaxmagf64":"_Float64",
"fminmagf64":"_Float64",
"__fminmagf64":"_Float64",
"fmaximumf64":"_Float64",
"__fmaximumf64":"_Float64",
"fminimumf64":"_Float64",
"__fminimumf64":"_Float64",
"fmaximum_numf64":"_Float64",
"__fmaximum_numf64":"_Float64",
"fminimum_numf64":"_Float64",
"__fminimum_numf64":"_Float64",
"fmaximum_magf64":"_Float64",
"__fmaximum_magf64":"_Float64",
"fminimum_magf64":"_Float64",
"__fminimum_magf64":"_Float64",
"fmaximum_mag_numf64":"_Float64",
"__fmaximum_mag_numf64":"_Float64",
"fminimum_mag_numf64":"_Float64",
"__fminimum_mag_numf64":"_Float64",
"totalorderf64":"int",
"totalordermagf64":"int",
"getpayloadf64":"_Float64",
"__getpayloadf64":"_Float64",
"setpayloadf64":"int",
"setpayloadsigf64":"int",
"acosf32x":"_Float32x",
"__acosf32x":"_Float32x",
"asinf32x":"_Float32x",
"__asinf32x":"_Float32x",
"atanf32x":"_Float32x",
"__atanf32x":"_Float32x",
"atan2f32x":"_Float32x",
"__atan2f32x":"_Float32x",
"cosf32x":"_Float32x",
"__cosf32x":"_Float32x",
"sinf32x":"_Float32x",
"__sinf32x":"_Float32x",
"tanf32x":"_Float32x",
"__tanf32x":"_Float32x",
"coshf32x":"_Float32x",
"__coshf32x":"_Float32x",
"sinhf32x":"_Float32x",
"__sinhf32x":"_Float32x",
"tanhf32x":"_Float32x",
"__tanhf32x":"_Float32x",
"sincosf32x":"void",
"__sincosf32x":"void",
"acoshf32x":"_Float32x",
"__acoshf32x":"_Float32x",
"asinhf32x":"_Float32x",
"__asinhf32x":"_Float32x",
"atanhf32x":"_Float32x",
"__atanhf32x":"_Float32x",
"expf32x":"_Float32x",
"__expf32x":"_Float32x",
"frexpf32x":"_Float32x",
"__frexpf32x":"_Float32x",
"ldexpf32x":"_Float32x",
"__ldexpf32x":"_Float32x",
"logf32x":"_Float32x",
"__logf32x":"_Float32x",
"log10f32x":"_Float32x",
"__log10f32x":"_Float32x",
"modff32x":"_Float32x",
"__modff32x":"_Float32x",
"exp10f32x":"_Float32x",
"__exp10f32x":"_Float32x",
"expm1f32x":"_Float32x",
"__expm1f32x":"_Float32x",
"log1pf32x":"_Float32x",
"__log1pf32x":"_Float32x",
"logbf32x":"_Float32x",
"__logbf32x":"_Float32x",
"exp2f32x":"_Float32x",
"__exp2f32x":"_Float32x",
"log2f32x":"_Float32x",
"__log2f32x":"_Float32x",
"powf32x":"_Float32x",
"__powf32x":"_Float32x",
"sqrtf32x":"_Float32x",
"__sqrtf32x":"_Float32x",
"hypotf32x":"_Float32x",
"__hypotf32x":"_Float32x",
"cbrtf32x":"_Float32x",
"__cbrtf32x":"_Float32x",
"ceilf32x":"_Float32x",
"__ceilf32x":"_Float32x",
"fabsf32x":"_Float32x",
"__fabsf32x":"_Float32x",
"floorf32x":"_Float32x",
"__floorf32x":"_Float32x",
"fmodf32x":"_Float32x",
"__fmodf32x":"_Float32x",
"copysignf32x":"_Float32x",
"__copysignf32x":"_Float32x",
"nanf32x":"_Float32x",
"__nanf32x":"_Float32x",
"j0f32x":"_Float32x",
"__j0f32x":"_Float32x",
"j1f32x":"_Float32x",
"__j1f32x":"_Float32x",
"jnf32x":"_Float32x",
"__jnf32x":"_Float32x",
"y0f32x":"_Float32x",
"__y0f32x":"_Float32x",
"y1f32x":"_Float32x",
"__y1f32x":"_Float32x",
"ynf32x":"_Float32x",
"__ynf32x":"_Float32x",
"erff32x":"_Float32x",
"__erff32x":"_Float32x",
"erfcf32x":"_Float32x",
"__erfcf32x":"_Float32x",
"lgammaf32x":"_Float32x",
"__lgammaf32x":"_Float32x",
"tgammaf32x":"_Float32x",
"__tgammaf32x":"_Float32x",
"lgammaf32x_r":"_Float32x",
"__lgammaf32x_r":"_Float32x",
"rintf32x":"_Float32x",
"__rintf32x":"_Float32x",
"nextafterf32x":"_Float32x",
"__nextafterf32x":"_Float32x",
"nextdownf32x":"_Float32x",
"__nextdownf32x":"_Float32x",
"nextupf32x":"_Float32x",
"__nextupf32x":"_Float32x",
"remainderf32x":"_Float32x",
"__remainderf32x":"_Float32x",
"scalbnf32x":"_Float32x",
"__scalbnf32x":"_Float32x",
"ilogbf32x":"int",
"__ilogbf32x":"int",
"llogbf32x":"long",
"__llogbf32x":"long",
"scalblnf32x":"_Float32x",
"__scalblnf32x":"_Float32x",
"nearbyintf32x":"_Float32x",
"__nearbyintf32x":"_Float32x",
"roundf32x":"_Float32x",
"__roundf32x":"_Float32x",
"truncf32x":"_Float32x",
"__truncf32x":"_Float32x",
"remquof32x":"_Float32x",
"__remquof32x":"_Float32x",
"lrintf32x":"long",
"__lrintf32x":"long",
"llrintf32x":"long long",
"__llrintf32x":"long long",
"lroundf32x":"long",
"__lroundf32x":"long",
"llroundf32x":"long long",
"__llroundf32x":"long long",
"fdimf32x":"_Float32x",
"__fdimf32x":"_Float32x",
"fmaxf32x":"_Float32x",
"__fmaxf32x":"_Float32x",
"fminf32x":"_Float32x",
"__fminf32x":"_Float32x",
"fmaf32x":"_Float32x",
"__fmaf32x":"_Float32x",
"roundevenf32x":"_Float32x",
"__roundevenf32x":"_Float32x",
"fromfpf32x":"__intmax_t",
"__fromfpf32x":"__intmax_t",
"ufromfpf32x":"__uintmax_t",
"__ufromfpf32x":"__uintmax_t",
"fromfpxf32x":"__intmax_t",
"__fromfpxf32x":"__intmax_t",
"ufromfpxf32x":"__uintmax_t",
"__ufromfpxf32x":"__uintmax_t",
"canonicalizef32x":"int",
"fmaxmagf32x":"_Float32x",
"__fmaxmagf32x":"_Float32x",
"fminmagf32x":"_Float32x",
"__fminmagf32x":"_Float32x",
"fmaximumf32x":"_Float32x",
"__fmaximumf32x":"_Float32x",
"fminimumf32x":"_Float32x",
"__fminimumf32x":"_Float32x",
"fmaximum_numf32x":"_Float32x",
"__fmaximum_numf32x":"_Float32x",
"fminimum_numf32x":"_Float32x",
"__fminimum_numf32x":"_Float32x",
"fmaximum_magf32x":"_Float32x",
"__fmaximum_magf32x":"_Float32x",
"fminimum_magf32x":"_Float32x",
"__fminimum_magf32x":"_Float32x",
"fmaximum_mag_numf32x":"_Float32x",
"__fmaximum_mag_numf32x":"_Float32x",
"fminimum_mag_numf32x":"_Float32x",
"__fminimum_mag_numf32x":"_Float32x",
"totalorderf32x":"int",
"totalordermagf32x":"int",
"getpayloadf32x":"_Float32x",
"__getpayloadf32x":"_Float32x",
"setpayloadf32x":"int",
"setpayloadsigf32x":"int",
"acosf64x":"_Float64x",
"__acosf64x":"_Float64x",
"asinf64x":"_Float64x",
"__asinf64x":"_Float64x",
"atanf64x":"_Float64x",
"__atanf64x":"_Float64x",
"atan2f64x":"_Float64x",
"__atan2f64x":"_Float64x",
"cosf64x":"_Float64x",
"__cosf64x":"_Float64x",
"sinf64x":"_Float64x",
"__sinf64x":"_Float64x",
"tanf64x":"_Float64x",
"__tanf64x":"_Float64x",
"coshf64x":"_Float64x",
"__coshf64x":"_Float64x",
"sinhf64x":"_Float64x",
"__sinhf64x":"_Float64x",
"tanhf64x":"_Float64x",
"__tanhf64x":"_Float64x",
"sincosf64x":"void",
"__sincosf64x":"void",
"acoshf64x":"_Float64x",
"__acoshf64x":"_Float64x",
"asinhf64x":"_Float64x",
"__asinhf64x":"_Float64x",
"atanhf64x":"_Float64x",
"__atanhf64x":"_Float64x",
"expf64x":"_Float64x",
"__expf64x":"_Float64x",
"frexpf64x":"_Float64x",
"__frexpf64x":"_Float64x",
"ldexpf64x":"_Float64x",
"__ldexpf64x":"_Float64x",
"logf64x":"_Float64x",
"__logf64x":"_Float64x",
"log10f64x":"_Float64x",
"__log10f64x":"_Float64x",
"modff64x":"_Float64x",
"__modff64x":"_Float64x",
"exp10f64x":"_Float64x",
"__exp10f64x":"_Float64x",
"expm1f64x":"_Float64x",
"__expm1f64x":"_Float64x",
"log1pf64x":"_Float64x",
"__log1pf64x":"_Float64x",
"logbf64x":"_Float64x",
"__logbf64x":"_Float64x",
"exp2f64x":"_Float64x",
"__exp2f64x":"_Float64x",
"log2f64x":"_Float64x",
"__log2f64x":"_Float64x",
"powf64x":"_Float64x",
"__powf64x":"_Float64x",
"sqrtf64x":"_Float64x",
"__sqrtf64x":"_Float64x",
"hypotf64x":"_Float64x",
"__hypotf64x":"_Float64x",
"cbrtf64x":"_Float64x",
"__cbrtf64x":"_Float64x",
"ceilf64x":"_Float64x",
"__ceilf64x":"_Float64x",
"fabsf64x":"_Float64x",
"__fabsf64x":"_Float64x",
"floorf64x":"_Float64x",
"__floorf64x":"_Float64x",
"fmodf64x":"_Float64x",
"__fmodf64x":"_Float64x",
"copysignf64x":"_Float64x",
"__copysignf64x":"_Float64x",
"nanf64x":"_Float64x",
"__nanf64x":"_Float64x",
"j0f64x":"_Float64x",
"__j0f64x":"_Float64x",
"j1f64x":"_Float64x",
"__j1f64x":"_Float64x",
"jnf64x":"_Float64x",
"__jnf64x":"_Float64x",
"y0f64x":"_Float64x",
"__y0f64x":"_Float64x",
"y1f64x":"_Float64x",
"__y1f64x":"_Float64x",
"ynf64x":"_Float64x",
"__ynf64x":"_Float64x",
"erff64x":"_Float64x",
"__erff64x":"_Float64x",
"erfcf64x":"_Float64x",
"__erfcf64x":"_Float64x",
"lgammaf64x":"_Float64x",
"__lgammaf64x":"_Float64x",
"tgammaf64x":"_Float64x",
"__tgammaf64x":"_Float64x",
"lgammaf64x_r":"_Float64x",
"__lgammaf64x_r":"_Float64x",
"rintf64x":"_Float64x",
"__rintf64x":"_Float64x",
"nextafterf64x":"_Float64x",
"__nextafterf64x":"_Float64x",
"nextdownf64x":"_Float64x",
"__nextdownf64x":"_Float64x",
"nextupf64x":"_Float64x",
"__nextupf64x":"_Float64x",
"remainderf64x":"_Float64x",
"__remainderf64x":"_Float64x",
"scalbnf64x":"_Float64x",
"__scalbnf64x":"_Float64x",
"ilogbf64x":"int",
"__ilogbf64x":"int",
"llogbf64x":"long",
"__llogbf64x":"long",
"scalblnf64x":"_Float64x",
"__scalblnf64x":"_Float64x",
"nearbyintf64x":"_Float64x",
"__nearbyintf64x":"_Float64x",
"roundf64x":"_Float64x",
"__roundf64x":"_Float64x",
"truncf64x":"_Float64x",
"__truncf64x":"_Float64x",
"remquof64x":"_Float64x",
"__remquof64x":"_Float64x",
"lrintf64x":"long",
"__lrintf64x":"long",
"llrintf64x":"long long",
"__llrintf64x":"long long",
"lroundf64x":"long",
"__lroundf64x":"long",
"llroundf64x":"long long",
"__llroundf64x":"long long",
"fdimf64x":"_Float64x",
"__fdimf64x":"_Float64x",
"fmaxf64x":"_Float64x",
"__fmaxf64x":"_Float64x",
"fminf64x":"_Float64x",
"__fminf64x":"_Float64x",
"fmaf64x":"_Float64x",
"__fmaf64x":"_Float64x",
"roundevenf64x":"_Float64x",
"__roundevenf64x":"_Float64x",
"fromfpf64x":"__intmax_t",
"__fromfpf64x":"__intmax_t",
"ufromfpf64x":"__uintmax_t",
"__ufromfpf64x":"__uintmax_t",
"fromfpxf64x":"__intmax_t",
"__fromfpxf64x":"__intmax_t",
"ufromfpxf64x":"__uintmax_t",
"__ufromfpxf64x":"__uintmax_t",
"canonicalizef64x":"int",
"fmaxmagf64x":"_Float64x",
"__fmaxmagf64x":"_Float64x",
"fminmagf64x":"_Float64x",
"__fminmagf64x":"_Float64x",
"fmaximumf64x":"_Float64x",
"__fmaximumf64x":"_Float64x",
"fminimumf64x":"_Float64x",
"__fminimumf64x":"_Float64x",
"fmaximum_numf64x":"_Float64x",
"__fmaximum_numf64x":"_Float64x",
"fminimum_numf64x":"_Float64x",
"__fminimum_numf64x":"_Float64x",
"fmaximum_magf64x":"_Float64x",
"__fmaximum_magf64x":"_Float64x",
"fminimum_magf64x":"_Float64x",
"__fminimum_magf64x":"_Float64x",
"fmaximum_mag_numf64x":"_Float64x",
"__fmaximum_mag_numf64x":"_Float64x",
"fminimum_mag_numf64x":"_Float64x",
"__fminimum_mag_numf64x":"_Float64x",
"totalorderf64x":"int",
"totalordermagf64x":"int",
"getpayloadf64x":"_Float64x",
"__getpayloadf64x":"_Float64x",
"setpayloadf64x":"int",
"setpayloadsigf64x":"int",
"fadd":"float",
"fdiv":"float",
"ffma":"float",
"fmul":"float",
"fsqrt":"float",
"fsub":"float",
"faddl":"float",
"fdivl":"float",
"ffmal":"float",
"fmull":"float",
"fsqrtl":"float",
"fsubl":"float",
"daddl":"double",
"ddivl":"double",
"dfmal":"double",
"dmull":"double",
"dsqrtl":"double",
"dsubl":"double",
"f32addf32x":"_Float32",
"f32divf32x":"_Float32",
"f32fmaf32x":"_Float32",
"f32mulf32x":"_Float32",
"f32sqrtf32x":"_Float32",
"f32subf32x":"_Float32",
"f32addf64":"_Float32",
"f32divf64":"_Float32",
"f32fmaf64":"_Float32",
"f32mulf64":"_Float32",
"f32sqrtf64":"_Float32",
"f32subf64":"_Float32",
"f32addf64x":"_Float32",
"f32divf64x":"_Float32",
"f32fmaf64x":"_Float32",
"f32mulf64x":"_Float32",
"f32sqrtf64x":"_Float32",
"f32subf64x":"_Float32",
"f32xaddf64":"_Float32x",
"f32xdivf64":"_Float32x",
"f32xfmaf64":"_Float32x",
"f32xmulf64":"_Float32x",
"f32xsqrtf64":"_Float32x",
"f32xsubf64":"_Float32x",
"f32xaddf64x":"_Float32x",
"f32xdivf64x":"_Float32x",
"f32xfmaf64x":"_Float32x",
"f32xmulf64x":"_Float32x",
"f32xsqrtf64x":"_Float32x",
"f32xsubf64x":"_Float32x",
"f64addf64x":"_Float64",
"f64divf64x":"_Float64",
"f64fmaf64x":"_Float64",
"f64mulf64x":"_Float64",
"f64sqrtf64x":"_Float64",
"f64subf64x":"_Float64",
"__iscanonicall":"int",
"iscanonical":[("int","(float)"),("int","(double)"),("int","(long double)")],
"issignaling":[("int","(float)"),("int","(double)"),("int","(long double)")],
"__ctype_get_mb_cur_max":"size_t",
"atof":"double",
"atoi":"int",
"atol":"long",
"atoll":"long long",
"strtod":"double",
"strtof":"float",
"strtold":"long double",
"strtof32":"_Float32",
"strtof64":"_Float64",
"strtof32x":"_Float32x",
"strtof64x":"_Float64x",
"strtol":"long",
"strtoul":"unsigned long",
"strtoq":"long long",
"strtouq":"unsigned long long",
"strtoll":"long long",
"strtoull":"unsigned long long",
"strfromd":"int",
"strfromf":"int",
"strfroml":"int",
"strfromf32":"int",
"strfromf64":"int",
"strfromf32x":"int",
"strfromf64x":"int",
"strtol_l":"long",
"strtoul_l":"unsigned long",
"strtoll_l":"long long",
"strtoull_l":"unsigned long long",
"strtod_l":"double",
"strtof_l":"float",
"strtold_l":"long double",
"strtof32_l":"_Float32",
"strtof64_l":"_Float64",
"strtof32x_l":"_Float32x",
"strtof64x_l":"_Float64x",
"l64a":"char *",
"a64l":"long",
"__bswap_16":"__uint16_t",
"__bswap_32":"__uint32_t",
"__bswap_64":"__uint64_t",
"__uint16_identity":"__uint16_t",
"__uint32_identity":"__uint32_t",
"__uint64_identity":"__uint64_t",
"select":"int",
"pselect":"int",
"random":"long",
"srandom":"void",
"initstate":"char *",
"setstate":"char *",
"random_r":"int",
"srandom_r":"int",
"initstate_r":"int",
"setstate_r":"int",
"rand":"int",
"srand":"void",
"rand_r":"int",
"drand48":"double",
"erand48":"double",
"lrand48":"long",
"nrand48":"long",
"mrand48":"long",
"jrand48":"long",
"srand48":"void",
"seed48":"unsigned short *",
"lcong48":"void",
"drand48_r":"int",
"erand48_r":"int",
"lrand48_r":"int",
"nrand48_r":"int",
"mrand48_r":"int",
"jrand48_r":"int",
"srand48_r":"int",
"seed48_r":"int",
"lcong48_r":"int",
"malloc":"void *",
"calloc":"void *",
"realloc":"void *",
"free":"void",
"reallocarray":[("void *","(void *, size_t, size_t)"),("void *","(void *, size_t, size_t)")],
"alloca":"void *",
"valloc":"void *",
"posix_memalign":"int",
"aligned_alloc":"void *",
"abort":"void",
"atexit":"int",
"at_quick_exit":"int",
"on_exit":"int",
"exit":"void",
"quick_exit":"void",
"_Exit":"void",
"getenv":"char *",
"secure_getenv":"char *",
"putenv":"int",
"setenv":"int",
"unsetenv":"int",
"clearenv":"int",
"mktemp":"char *",
"mkstemp":"int",
"mkstemp64":"int",
"mkstemps":"int",
"mkstemps64":"int",
"mkdtemp":"char *",
"mkostemp":"int",
"mkostemp64":"int",
"mkostemps":"int",
"mkostemps64":"int",
"system":"int",
"canonicalize_file_name":"char *",
"realpath":"char *",
"bsearch":"void *",
"qsort":"void",
"qsort_r":"void",
"abs":[("int","(int)"),("long","(long)"),("long long","(long long)"),("double","(double)"),("float","(float)"),("long double","(long double)"),("__int128","(__int128)"),("__float128","(__float128)")],
"labs":"long",
"llabs":"long long",
"div":[("div_t","(int, int)"),("ldiv_t","(long, long)"),("lldiv_t","(long long, long long)")],
"ldiv":"ldiv_t",
"lldiv":"lldiv_t",
"ecvt":"char *",
"fcvt":"char *",
"gcvt":"char *",
"qecvt":"char *",
"qfcvt":"char *",
"qgcvt":"char *",
"ecvt_r":"int",
"fcvt_r":"int",
"qecvt_r":"int",
"qfcvt_r":"int",
"mblen":"int",
"mbtowc":"int",
"wctomb":"int",
"mbstowcs":"size_t",
"wcstombs":"size_t",
"rpmatch":"int",
"getsubopt":"int",
"posix_openpt":"int",
"grantpt":"int",
"unlockpt":"int",
"ptsname":"char *",
"ptsname_r":"int",
"getpt":"int",
"getloadavg":"int",
"fpclassify":[("int","(float)"),("int","(double)"),("int","(long double)")],
"isfinite":[("bool","(float)"),("bool","(double)"),("bool","(long double)")],
"isinf":[("bool","(float)"),("bool","(double)"),("bool","(long double)")],
"isnan":[("bool","(float)"),("bool","(double)"),("bool","(long double)")],
"isnormal":[("bool","(float)"),("bool","(double)"),("bool","(long double)")],
"signbit":[("bool","(float)"),("bool","(double)"),("bool","(long double)")],
"isgreater":[("bool","(float, float)"),("bool","(double, double)"),("bool","(long double, long double)")],
"isgreaterequal":[("bool","(float, float)"),("bool","(double, double)"),("bool","(long double, long double)")],
"isless":[("bool","(float, float)"),("bool","(double, double)"),("bool","(long double, long double)")],
"islessequal":[("bool","(float, float)"),("bool","(double, double)"),("bool","(long double, long double)")],
"islessgreater":[("bool","(float, float)"),("bool","(double, double)"),("bool","(long double, long double)")],
"isunordered":[("bool","(float, float)"),("bool","(double, double)"),("bool","(long double, long double)")],
"setjmp":"int",
"__sigsetjmp":[("int","(struct __jmp_buf_tag *, int)"),("int","(struct __jmp_buf_tag *, int)")],
"_setjmp":"int",
"longjmp":"void",
"_longjmp":"void",
"siglongjmp":"void",
"__sysv_signal":"__sighandler_t",
"sysv_signal":"__sighandler_t",
"signal":"__sighandler_t",
"kill":"int",
"killpg":"int",
"raise":"int",
"ssignal":"__sighandler_t",
"gsignal":"int",
"psignal":"void",
"psiginfo":"void",
"sigpause":"int",
"sigblock":"int",
"sigsetmask":"int",
"siggetmask":"int",
"sigemptyset":"int",
"sigfillset":"int",
"sigaddset":"int",
"sigdelset":"int",
"sigismember":"int",
"sigisemptyset":"int",
"sigandset":"int",
"sigorset":"int",
"sigprocmask":"int",
"sigsuspend":"int",
"sigaction":"int",
"sigpending":"int",
"sigwait":"int",
"sigwaitinfo":"int",
"sigtimedwait":"int",
"sigqueue":"int",
"sigreturn":"int",
"siginterrupt":"int",
"access":"int",
"euidaccess":"int",
"eaccess":"int",
"execveat":"int",
"faccessat":"int",
"lseek":"__off_t",
"lseek64":"__off64_t",
"close":"int",
"closefrom":"void",
"read":"ssize_t",
"write":"ssize_t",
"pread":"ssize_t",
"pwrite":"ssize_t",
"pread64":"ssize_t",
"pwrite64":"ssize_t",
"pipe":"int",
"pipe2":"int",
"alarm":"unsigned int",
"sleep":"unsigned int",
"ualarm":"__useconds_t",
"usleep":"int",
"pause":"int",
"chown":"int",
"fchown":"int",
"lchown":"int",
"fchownat":"int",
"chdir":"int",
"fchdir":"int",
"getcwd":"char *",
"get_current_dir_name":"char *",
"getwd":"char *",
"dup":"int",
"dup2":"int",
"dup3":"int",
"execve":"int",
"fexecve":"int",
"execv":"int",
"execle":"int",
"execl":"int",
"execvp":"int",
"execlp":"int",
"execvpe":"int",
"nice":"int",
"_exit":"void",
"pathconf":"long",
"fpathconf":"long",
"sysconf":"long",
"confstr":"size_t",
"getpid":"__pid_t",
"getppid":"__pid_t",
"getpgrp":"__pid_t",
"__getpgid":"__pid_t",
"getpgid":"__pid_t",
"setpgid":"int",
"setpgrp":"int",
"setsid":"__pid_t",
"getsid":"__pid_t",
"getuid":"__uid_t",
"geteuid":"__uid_t",
"getgid":"__gid_t",
"getegid":"__gid_t",
"getgroups":"int",
"group_member":"int",
"setuid":"int",
"setreuid":"int",
"seteuid":"int",
"setgid":"int",
"setregid":"int",
"setegid":"int",
"getresuid":"int",
"getresgid":"int",
"setresuid":"int",
"setresgid":"int",
"fork":"__pid_t",
"vfork":"__pid_t",
"_Fork":"__pid_t",
"ttyname":"char *",
"ttyname_r":"int",
"isatty":"int",
"ttyslot":"int",
"link":"int",
"linkat":"int",
"symlink":"int",
"readlink":"ssize_t",
"symlinkat":"int",
"readlinkat":"ssize_t",
"unlink":"int",
"unlinkat":"int",
"rmdir":"int",
"tcgetpgrp":"__pid_t",
"tcsetpgrp":"int",
"getlogin":"char *",
"getlogin_r":"int",
"setlogin":"int",
"getopt":"int",
"gethostname":"int",
"sethostname":"int",
"sethostid":"int",
"getdomainname":"int",
"setdomainname":"int",
"vhangup":"int",
"revoke":"int",
"profil":"int",
"acct":"int",
"getusershell":"char *",
"endusershell":"void",
"setusershell":"void",
"daemon":"int",
"chroot":"int",
"getpass":"char *",
"fsync":"int",
"syncfs":"int",
"gethostid":"long",
"sync":"void",
"getpagesize":"int",
"getdtablesize":"int",
"truncate":"int",
"truncate64":"int",
"ftruncate":"int",
"ftruncate64":"int",
"brk":"int",
"sbrk":"void *",
"syscall":"long",
"lockf":"int",
"lockf64":"int",
"copy_file_range":"ssize_t",
"fdatasync":"int",
"crypt":"char *",
"swab":"void",
"getentropy":"int",
"close_range":"int",
"gettid":"__pid_t",
"sigaltstack":"int",
"sigstack":"int",
"sighold":"int",
"sigrelse":"int",
"sigignore":"int",
"sigset":"__sighandler_t",
"pthread_sigmask":"int",
"pthread_kill":"int",
"pthread_sigqueue":"int",
"__libc_current_sigrtmin":"int",
"__libc_current_sigrtmax":"int",
"tgkill":"int",
"remove":"int",
"rename":"int",
"renameat":"int",
"renameat2":"int",
"fclose":"int",
"tmpfile":"FILE *",
"tmpfile64":"FILE *",
"tmpnam":"char *",
"tmpnam_r":"char *",
"tempnam":"char *",
"fflush":"int",
"fflush_unlocked":"int",
"fcloseall":"int",
"fopen":"FILE *",
"freopen":"FILE *",
"fopen64":"FILE *",
"freopen64":"FILE *",
"fdopen":"FILE *",
"fopencookie":"FILE *",
"fmemopen":"FILE *",
"open_memstream":"FILE *",
"setbuf":"void",
"setvbuf":"int",
"setbuffer":"void",
"setlinebuf":"void",
"fprintf":"int",
"printf":"int",
"sprintf":"int",
"vfprintf":"int",
"vprintf":"int",
"vsprintf":"int",
"snprintf":"int",
"vsnprintf":"int",
"vasprintf":"int",
"__asprintf":"int",
"asprintf":"int",
"vdprintf":"int",
"dprintf":"int",
"fscanf":[("int","(FILE *__restrict, const char *__restrict, ...)"),("int","(FILE *__restrict, const char *__restrict, ...)")],
"scanf":[("int","(const char *__restrict, ...)"),("int","(const char *__restrict, ...)")],
"sscanf":[("int","(const char *__restrict, const char *__restrict, ...)"),("int","(const char *__restrict, const char *__restrict, ...)")],
"vfscanf":[("int","(FILE *__restrict, const char *__restrict, __va_list_tag *)"),("int","(FILE *__restrict, const char *__restrict, __va_list_tag *)")],
"vscanf":[("int","(const char *__restrict, __va_list_tag *)"),("int","(const char *__restrict, __va_list_tag *)")],
"vsscanf":[("int","(const char *__restrict, const char *__restrict, __va_list_tag *)"),("int","(const char *__restrict, const char *__restrict, __va_list_tag *)")],
"fgetc":"int",
"getc":"int",
"getchar":"int",
"getc_unlocked":"int",
"getchar_unlocked":"int",
"fgetc_unlocked":"int",
"fputc":"int",
"putc":"int",
"putchar":"int",
"fputc_unlocked":"int",
"putc_unlocked":"int",
"putchar_unlocked":"int",
"getw":"int",
"putw":"int",
"fgets":"char *",
"fgets_unlocked":"char *",
"__getdelim":"__ssize_t",
"getdelim":"__ssize_t",
"getline":[("__ssize_t","(char **__restrict, size_t *__restrict, FILE *__restrict)"),("basic_istream<char> &","(basic_istream<char> &, basic_string<char> &, char)"),("basic_istream<wchar_t> &","(basic_istream<wchar_t> &, basic_string<wchar_t> &, wchar_t)")],
"fputs":"int",
"puts":"int",
"ungetc":"int",
"fread":"size_t",
"fwrite":"size_t",
"fputs_unlocked":"int",
"fread_unlocked":"size_t",
"fwrite_unlocked":"size_t",
"fseek":"int",
"ftell":"long",
"rewind":"void",
"fseeko":"int",
"ftello":"__off_t",
"fgetpos":"int",
"fsetpos":"int",
"fseeko64":"int",
"ftello64":"__off64_t",
"fgetpos64":"int",
"fsetpos64":"int",
"clearerr":"void",
"feof":"int",
"ferror":"int",
"clearerr_unlocked":"void",
"feof_unlocked":"int",
"ferror_unlocked":"int",
"perror":"void",
"fileno":"int",
"fileno_unlocked":"int",
"pclose":"int",
"popen":"FILE *",
"ctermid":"char *",
"cuserid":"char *",
"obstack_printf":"int",
"obstack_vprintf":"int",
"flockfile":"void",
"ftrylockfile":"int",
"funlockfile":"void",
"__uflow":"int",
"__overflow":"int",
"memcpy":"void *",
"memmove":"void *",
"memccpy":"void *",
"memset":"void *",
"memcmp":"int",
"__memcmpeq":"int",
"memchr":[("void *","(void *, int, size_t)"),("const void *","(const void *, int, size_t)")],
"rawmemchr":[("void *","(void *, int)"),("const void *","(const void *, int)")],
"memrchr":[("void *","(void *, int, size_t)"),("const void *","(const void *, int, size_t)")],
"strcpy":"char *",
"strncpy":"char *",
"strcat":"char *",
"strncat":"char *",
"strcmp":"int",
"strncmp":"int",
"strcoll":"int",
"strxfrm":"size_t",
"strcoll_l":"int",
"strxfrm_l":"size_t",
"strdup":"char *",
"strndup":"char *",
"strchr":[("char *","(char *, int)"),("const char *","(const char *, int)")],
"strrchr":[("char *","(char *, int)"),("const char *","(const char *, int)")],
"strchrnul":[("char *","(char *, int)"),("const char *","(const char *, int)")],
"strcspn":"size_t",
"strspn":"size_t",
"strpbrk":[("char *","(char *, const char *)"),("const char *","(const char *, const char *)")],
"strstr":[("char *","(char *, const char *)"),("const char *","(const char *, const char *)")],
"strtok":"char *",
"__strtok_r":"char *",
"strtok_r":"char *",
"strcasestr":[("char *","(char *, const char *)"),("const char *","(const char *, const char *)")],
"memmem":"void *",
"__mempcpy":"void *",
"mempcpy":"void *",
"strlen":"size_t",
"strnlen":"size_t",
"strerror":"char *",
"strerror_r":"char *",
"strerrordesc_np":"const char *",
"strerrorname_np":"const char *",
"strerror_l":"char *",
"bcmp":"int",
"bcopy":"void",
"bzero":"void",
"index":"char *",
"rindex":"char *",
"ffs":"int",
"ffsl":"int",
"ffsll":"int",
"strcasecmp":"int",
"strncasecmp":"int",
"strcasecmp_l":"int",
"strncasecmp_l":"int",
"explicit_bzero":"void",
"strsep":"char *",
"strsignal":"char *",
"sigabbrev_np":"const char *",
"sigdescr_np":"const char *",
"__stpcpy":"char *",
"stpcpy":"char *",
"__stpncpy":"char *",
"stpncpy":"char *",
"strverscmp":"int",
"strfry":"char *",
"memfrob":"void *",
"basename":[("char *","(char *)"),("const char *","(const char *)")],
"clock_adjtime":"int",
"clock":"clock_t",
"time":"time_t",
"difftime":"double",
"mktime":"time_t",
"strftime":"size_t",
"strptime":"char *",
"strftime_l":"size_t",
"strptime_l":"char *",
"gmtime":"struct tm *",
"localtime":"struct tm *",
"gmtime_r":"struct tm *",
"localtime_r":"struct tm *",
"asctime":"char *",
"ctime":"char *",
"asctime_r":"char *",
"ctime_r":"char *",
"tzset":"void",
"timegm":"time_t",
"timelocal":"time_t",
"dysize":"int",
"nanosleep":"int",
"clock_getres":"int",
"clock_gettime":"int",
"clock_settime":"int",
"clock_nanosleep":"int",
"clock_getcpuclockid":"int",
"timer_create":"int",
"timer_delete":"int",
"timer_settime":"int",
"timer_gettime":"int",
"timer_getoverrun":"int",
"timespec_get":"int",
"timespec_getres":"int",
"getdate":"struct tm *",
"getdate_r":"int",
"wcscpy":"wchar_t *",
"wcsncpy":"wchar_t *",
"wcscat":"wchar_t *",
"wcsncat":"wchar_t *",
"wcscmp":"int",
"wcsncmp":"int",
"wcscasecmp":"int",
"wcsncasecmp":"int",
"wcscasecmp_l":"int",
"wcsncasecmp_l":"int",
"wcscoll":"int",
"wcsxfrm":"size_t",
"wcscoll_l":"int",
"wcsxfrm_l":"size_t",
"wcsdup":"wchar_t *",
"wcschr":[("wchar_t *","(const wchar_t *, wchar_t)"),("wchar_t *","(wchar_t *, wchar_t)")],
"wcsrchr":[("wchar_t *","(const wchar_t *, wchar_t)"),("wchar_t *","(wchar_t *, wchar_t)")],
"wcschrnul":"wchar_t *",
"wcscspn":"size_t",
"wcsspn":"size_t",
"wcspbrk":[("wchar_t *","(const wchar_t *, const wchar_t *)"),("wchar_t *","(wchar_t *, const wchar_t *)")],
"wcsstr":[("wchar_t *","(const wchar_t *, const wchar_t *)"),("wchar_t *","(wchar_t *, const wchar_t *)")],
"wcstok":"wchar_t *",
"wcslen":"size_t",
"wcswcs":"wchar_t *",
"wcsnlen":"size_t",
"wmemchr":[("wchar_t *","(const wchar_t *, wchar_t, size_t)"),("wchar_t *","(wchar_t *, wchar_t, std::size_t)")],
"wmemcmp":"int",
"wmemcpy":"wchar_t *",
"wmemmove":"wchar_t *",
"wmemset":"wchar_t *",
"wmempcpy":"wchar_t *",
"btowc":"wint_t",
"wctob":"int",
"mbsinit":"int",
"mbrtowc":"size_t",
"wcrtomb":"size_t",
"__mbrlen":"size_t",
"mbrlen":"size_t",
"mbsrtowcs":"size_t",
"wcsrtombs":"size_t",
"mbsnrtowcs":"size_t",
"wcsnrtombs":"size_t",
"wcwidth":"int",
"wcswidth":"int",
"wcstod":"double",
"wcstof":"float",
"wcstold":"long double",
"wcstof32":"_Float32",
"wcstof64":"_Float64",
"wcstof32x":"_Float32x",
"wcstof64x":"_Float64x",
"wcstol":"long",
"wcstoul":"unsigned long",
"wcstoll":"long long",
"wcstoull":"unsigned long long",
"wcstoq":"long long",
"wcstouq":"unsigned long long",
"wcstol_l":"long",
"wcstoul_l":"unsigned long",
"wcstoll_l":"long long",
"wcstoull_l":"unsigned long long",
"wcstod_l":"double",
"wcstof_l":"float",
"wcstold_l":"long double",
"wcstof32_l":"_Float32",
"wcstof64_l":"_Float64",
"wcstof32x_l":"_Float32x",
"wcstof64x_l":"_Float64x",
"wcpcpy":"wchar_t *",
"wcpncpy":"wchar_t *",
"open_wmemstream":"__FILE *",
"fwide":"int",
"fwprintf":"int",
"wprintf":"int",
"swprintf":"int",
"vfwprintf":"int",
"vwprintf":"int",
"vswprintf":"int",
"fwscanf":[("int","(__FILE *__restrict, const wchar_t *__restrict, ...)"),("int","(__FILE *__restrict, const wchar_t *__restrict, ...)")],
"wscanf":[("int","(const wchar_t *__restrict, ...)"),("int","(const wchar_t *__restrict, ...)")],
"swscanf":[("int","(const wchar_t *__restrict, const wchar_t *__restrict, ...)"),("int","(const wchar_t *__restrict, const wchar_t *__restrict, ...)")],
"vfwscanf":[("int","(__FILE *__restrict, const wchar_t *__restrict, __va_list_tag *)"),("int","(__FILE *__restrict, const wchar_t *__restrict, __va_list_tag *)")],
"vwscanf":[("int","(const wchar_t *__restrict, __va_list_tag *)"),("int","(const wchar_t *__restrict, __va_list_tag *)")],
"vswscanf":[("int","(const wchar_t *__restrict, const wchar_t *__restrict, __va_list_tag *)"),("int","(const wchar_t *__restrict, const wchar_t *__restrict, __va_list_tag *)")],
"fgetwc":"wint_t",
"getwc":"wint_t",
"getwchar":"wint_t",
"fputwc":"wint_t",
"putwc":"wint_t",
"putwchar":"wint_t",
"fgetws":"wchar_t *",
"fputws":"int",
"ungetwc":"wint_t",
"getwc_unlocked":"wint_t",
"getwchar_unlocked":"wint_t",
"fgetwc_unlocked":"wint_t",
"fputwc_unlocked":"wint_t",
"putwc_unlocked":"wint_t",
"putwchar_unlocked":"wint_t",
"fgetws_unlocked":"wchar_t *",
"fputws_unlocked":"int",
"wcsftime":"size_t",
"wcsftime_l":"size_t",
"iswalnum":"int",
"iswalpha":"int",
"iswcntrl":"int",
"iswdigit":"int",
"iswgraph":"int",
"iswlower":"int",
"iswprint":"int",
"iswpunct":"int",
"iswspace":"int",
"iswupper":"int",
"iswxdigit":"int",
"iswblank":"int",
"wctype":"wctype_t",
"iswctype":"int",
"towlower":"wint_t",
"towupper":"wint_t",
"wctrans":"wctrans_t",
"towctrans":"wint_t",
"iswalnum_l":"int",
"iswalpha_l":"int",
"iswcntrl_l":"int",
"iswdigit_l":"int",
"iswgraph_l":"int",
"iswlower_l":"int",
"iswprint_l":"int",
"iswpunct_l":"int",
"iswspace_l":"int",
"iswupper_l":"int",
"iswxdigit_l":"int",
"iswblank_l":"int",
"wctype_l":"wctype_t",
"iswctype_l":"int",
"towlower_l":"wint_t",
"towupper_l":"wint_t",
"wctrans_l":"wctrans_t",
"towctrans_l":"wint_t",
"set_terminate":"std::terminate_handler",
"get_terminate":"std::terminate_handler",
"terminate":"void",
"set_unexpected":"std::unexpected_handler",
"get_unexpected":"std::unexpected_handler",
"unexpected":"void",
"uncaught_exception":"bool",
"uncaught_exceptions":"int",
"__verbose_terminate_handler":"void",
"__cxa_allocate_exception":"void *",
"__cxa_free_exception":"void",
"__cxa_init_primary_exception":"__cxxabiv1::__cxa_refcounted_exception *",
"_Hash_bytes":"std::size_t",
"_Fnv_hash_bytes":"std::size_t",
"set_new_handler":"std::new_handler",
"get_new_handler":"std::new_handler",
"current_exception":[("std::__exception_ptr::exception_ptr","()"),("std::__exception_ptr::exception_ptr","()")],
"rethrow_exception":[("void","(std::__exception_ptr::exception_ptr)"),("void","(std::__exception_ptr::exception_ptr)")],
"swap":[("void","(std::__exception_ptr::exception_ptr &, std::__exception_ptr::exception_ptr &)"),("void","(std::_Bit_reference, std::_Bit_reference)"),("void","(std::_Bit_reference, bool &)"),("void","(bool &, std::_Bit_reference)"),("void","(std::thread &, std::thread &)")],
"__rethrow_if_nested_impl":"void",
"__throw_bad_exception":"void",
"__throw_bad_alloc":"void",
"__throw_bad_array_new_length":"void",
"__throw_bad_cast":"void",
"__throw_bad_typeid":"void",
"__throw_logic_error":"void",
"__throw_domain_error":"void",
"__throw_invalid_argument":"void",
"__throw_length_error":"void",
"__throw_out_of_range":"void",
"__throw_out_of_range_fmt":"void",
"__throw_runtime_error":"void",
"__throw_range_error":"void",
"__throw_overflow_error":"void",
"__throw_underflow_error":"void",
"__throw_ios_failure":[("void","(const char *)"),("void","(const char *, int)")],
"__throw_system_error":"void",
"__throw_future_error":[("void","(int)"),("void","(int)")],
"__throw_bad_function_call":"void",
"__iter_less_iter":"__gnu_cxx::__ops::_Iter_less_iter",
"__iter_less_val":"__gnu_cxx::__ops::_Iter_less_val",
"__iter_comp_val":[("__gnu_cxx::__ops::_Iter_less_val","(__gnu_cxx::__ops::_Iter_less_iter)"),("__gnu_cxx::__ops::_Iter_equal_to_val","(__gnu_cxx::__ops::_Iter_equal_to_iter)")],
"__val_less_iter":"__gnu_cxx::__ops::_Val_less_iter",
"__val_comp_iter":"__gnu_cxx::__ops::_Val_less_iter",
"__iter_equal_to_iter":"__gnu_cxx::__ops::_Iter_equal_to_iter",
"__iter_equal_to_val":"__gnu_cxx::__ops::_Iter_equal_to_val",
"__fill_a1":[("void","(std::_Bit_iterator, std::_Bit_iterator, const bool &)"),("void","(std::_Bit_iterator, std::_Bit_iterator, const bool &)")],
"__size_to_integer":[("int","(int)"),("unsigned int","(unsigned int)"),("long","(long)"),("unsigned long","(unsigned long)"),("long long","(long long)"),("unsigned long long","(unsigned long long)"),("__int128","(__int128)"),("unsigned __int128","(unsigned __int128)"),("long long","(float)"),("long long","(double)"),("long long","(long double)"),("long long","(__float128)")],
"__lg":[("int","(int)"),("unsigned int","(unsigned int)"),("long","(long)"),("unsigned long","(unsigned long)"),("long long","(long long)"),("unsigned long long","(unsigned long long)")],
"__uselocale":"void *",
"__convert_from_v":"int",
"clone":"int",
"unshare":"int",
"sched_getcpu":"int",
"getcpu":"int",
"setns":"int",
"__sched_cpucount":"int",
"__sched_cpualloc":"cpu_set_t *",
"__sched_cpufree":"void",
"sched_setparam":"int",
"sched_getparam":"int",
"sched_setscheduler":"int",
"sched_getscheduler":"int",
"sched_yield":"int",
"sched_get_priority_max":"int",
"sched_get_priority_min":"int",
"sched_rr_get_interval":"int",
"sched_setaffinity":"int",
"sched_getaffinity":"int",
"pthread_create":"int",
"pthread_exit":"void",
"pthread_join":"int",
"pthread_tryjoin_np":"int",
"pthread_timedjoin_np":"int",
"pthread_clockjoin_np":"int",
"pthread_detach":"int",
"pthread_self":"pthread_t",
"pthread_equal":"int",
"pthread_attr_init":"int",
"pthread_attr_destroy":"int",
"pthread_attr_getdetachstate":"int",
"pthread_attr_setdetachstate":"int",
"pthread_attr_getguardsize":"int",
"pthread_attr_setguardsize":"int",
"pthread_attr_getschedparam":"int",
"pthread_attr_setschedparam":"int",
"pthread_attr_getschedpolicy":"int",
"pthread_attr_setschedpolicy":"int",
"pthread_attr_getinheritsched":"int",
"pthread_attr_setinheritsched":"int",
"pthread_attr_getscope":"int",
"pthread_attr_setscope":"int",
"pthread_attr_getstackaddr":"int",
"pthread_attr_setstackaddr":"int",
"pthread_attr_getstacksize":"int",
"pthread_attr_setstacksize":"int",
"pthread_attr_getstack":"int",
"pthread_attr_setstack":"int",
"pthread_attr_setaffinity_np":"int",
"pthread_attr_getaffinity_np":"int",
"pthread_getattr_default_np":"int",
"pthread_attr_setsigmask_np":"int",
"pthread_attr_getsigmask_np":"int",
"pthread_setattr_default_np":"int",
"pthread_getattr_np":"int",
"pthread_setschedparam":"int",
"pthread_getschedparam":"int",
"pthread_setschedprio":"int",
"pthread_getname_np":"int",
"pthread_setname_np":"int",
"pthread_getconcurrency":"int",
"pthread_setconcurrency":"int",
"pthread_yield":[("int","()"),("int","()")],
"pthread_setaffinity_np":"int",
"pthread_getaffinity_np":"int",
"pthread_once":"int",
"pthread_setcancelstate":"int",
"pthread_setcanceltype":"int",
"pthread_cancel":"int",
"pthread_testcancel":"void",
"pthread_mutex_init":"int",
"pthread_mutex_destroy":"int",
"pthread_mutex_trylock":"int",
"pthread_mutex_lock":"int",
"pthread_mutex_timedlock":"int",
"pthread_mutex_clocklock":"int",
"pthread_mutex_unlock":"int",
"pthread_mutex_getprioceiling":"int",
"pthread_mutex_setprioceiling":"int",
"pthread_mutex_consistent":"int",
"pthread_mutex_consistent_np":"int",
"pthread_mutexattr_init":"int",
"pthread_mutexattr_destroy":"int",
"pthread_mutexattr_getpshared":"int",
"pthread_mutexattr_setpshared":"int",
"pthread_mutexattr_gettype":"int",
"pthread_mutexattr_settype":"int",
"pthread_mutexattr_getprotocol":"int",
"pthread_mutexattr_setprotocol":"int",
"pthread_mutexattr_getprioceiling":"int",
"pthread_mutexattr_setprioceiling":"int",
"pthread_mutexattr_getrobust":"int",
"pthread_mutexattr_getrobust_np":"int",
"pthread_mutexattr_setrobust":"int",
"pthread_mutexattr_setrobust_np":"int",
"pthread_rwlock_init":"int",
"pthread_rwlock_destroy":"int",
"pthread_rwlock_rdlock":"int",
"pthread_rwlock_tryrdlock":"int",
"pthread_rwlock_timedrdlock":"int",
"pthread_rwlock_clockrdlock":"int",
"pthread_rwlock_wrlock":"int",
"pthread_rwlock_trywrlock":"int",
"pthread_rwlock_timedwrlock":"int",
"pthread_rwlock_clockwrlock":"int",
"pthread_rwlock_unlock":"int",
"pthread_rwlockattr_init":"int",
"pthread_rwlockattr_destroy":"int",
"pthread_rwlockattr_getpshared":"int",
"pthread_rwlockattr_setpshared":"int",
"pthread_rwlockattr_getkind_np":"int",
"pthread_rwlockattr_setkind_np":"int",
"pthread_cond_init":"int",
"pthread_cond_destroy":"int",
"pthread_cond_signal":"int",
"pthread_cond_broadcast":"int",
"pthread_cond_wait":"int",
"pthread_cond_timedwait":"int",
"pthread_cond_clockwait":"int",
"pthread_condattr_init":"int",
"pthread_condattr_destroy":"int",
"pthread_condattr_getpshared":"int",
"pthread_condattr_setpshared":"int",
"pthread_condattr_getclock":"int",
"pthread_condattr_setclock":"int",
"pthread_spin_init":"int",
"pthread_spin_destroy":"int",
"pthread_spin_lock":"int",
"pthread_spin_trylock":"int",
"pthread_spin_unlock":"int",
"pthread_barrier_init":"int",
"pthread_barrier_destroy":"int",
"pthread_barrier_wait":"int",
"pthread_barrierattr_init":"int",
"pthread_barrierattr_destroy":"int",
"pthread_barrierattr_getpshared":"int",
"pthread_barrierattr_setpshared":"int",
"pthread_key_create":"int",
"pthread_key_delete":"int",
"pthread_getspecific":"void *",
"pthread_setspecific":"int",
"pthread_getcpuclockid":"int",
"pthread_atfork":"int",
"__gthread_active_p":"int",
"__gthread_create":"int",
"__gthread_join":"int",
"__gthread_detach":"int",
"__gthread_equal":"int",
"__gthread_self":"__gthread_t",
"__gthread_yield":"int",
"__gthread_once":"int",
"__gthread_key_create":"int",
"__gthread_key_delete":"int",
"__gthread_getspecific":"void *",
"__gthread_setspecific":"int",
"__gthread_mutex_init_function":"void",
"__gthread_mutex_destroy":"int",
"__gthread_mutex_lock":"int",
"__gthread_mutex_trylock":"int",
"__gthread_mutex_timedlock":"int",
"__gthread_mutex_unlock":"int",
"__gthread_recursive_mutex_lock":"int",
"__gthread_recursive_mutex_trylock":"int",
"__gthread_recursive_mutex_timedlock":"int",
"__gthread_recursive_mutex_unlock":"int",
"__gthread_recursive_mutex_destroy":"int",
"__gthread_cond_broadcast":"int",
"__gthread_cond_signal":"int",
"__gthread_cond_wait":"int",
"__gthread_cond_timedwait":"int",
"__gthread_cond_wait_recursive":"int",
"__gthread_cond_destroy":"int",
"__is_single_threaded":"bool",
"__exchange_and_add":"_Atomic_word",
"__atomic_add":"void",
"__exchange_and_add_single":"_Atomic_word",
"__atomic_add_single":"void",
"__exchange_and_add_dispatch":"_Atomic_word",
"__atomic_add_dispatch":"void",
"stoi":[("int","(const std::string &, std::size_t *, int)"),("int","(const std::wstring &, std::size_t *, int)")],
"stol":[("long","(const std::string &, std::size_t *, int)"),("long","(const std::wstring &, std::size_t *, int)")],
"stoul":[("unsigned long","(const std::string &, std::size_t *, int)"),("unsigned long","(const std::wstring &, std::size_t *, int)")],
"stoll":[("long long","(const std::string &, std::size_t *, int)"),("long long","(const std::wstring &, std::size_t *, int)")],
"stoull":[("unsigned long long","(const std::string &, std::size_t *, int)"),("unsigned long long","(const std::wstring &, std::size_t *, int)")],
"stof":[("float","(const std::string &, std::size_t *)"),("float","(const std::wstring &, std::size_t *)")],
"stod":[("double","(const std::string &, std::size_t *)"),("double","(const std::wstring &, std::size_t *)")],
"stold":[("long double","(const std::string &, std::size_t *)"),("long double","(const std::wstring &, std::size_t *)")],
"to_string":[("std::string","(int)"),("std::string","(unsigned int)"),("std::string","(long)"),("std::string","(unsigned long)"),("std::string","(long long)"),("std::string","(unsigned long long)"),("std::string","(float)"),("std::string","(double)"),("std::string","(long double)")],
"to_wstring":[("std::wstring","(int)"),("std::wstring","(unsigned int)"),("std::wstring","(long)"),("std::wstring","(unsigned long)"),("std::wstring","(long long)"),("std::wstring","(unsigned long long)"),("std::wstring","(float)"),("std::wstring","(double)"),("std::wstring","(long double)")],
"generic_category":"const std::_V2::error_category &",
"system_category":"const std::_V2::error_category &",
"make_error_code":[("std::error_code","(std::errc)"),("std::error_code","(std::errc)"),("std::error_code","(std::io_errc)"),("std::error_code","(std::future_errc)")],
"make_error_condition":[("std::error_condition","(std::errc)"),("std::error_condition","(std::errc)"),("std::error_condition","(std::io_errc)"),("std::error_condition","(std::future_errc)")],
"iostream_category":"const std::_V2::error_category &",
"boolalpha":"std::ios_base &",
"noboolalpha":"std::ios_base &",
"showbase":"std::ios_base &",
"noshowbase":"std::ios_base &",
"showpoint":"std::ios_base &",
"noshowpoint":"std::ios_base &",
"showpos":"std::ios_base &",
"noshowpos":"std::ios_base &",
"skipws":"std::ios_base &",
"noskipws":"std::ios_base &",
"uppercase":"std::ios_base &",
"nouppercase":"std::ios_base &",
"unitbuf":"std::ios_base &",
"nounitbuf":"std::ios_base &",
"internal":"std::ios_base &",
"left":"std::ios_base &",
"right":"std::ios_base &",
"dec":"std::ios_base &",
"hex":"std::ios_base &",
"oct":"std::ios_base &",
"fixed":"std::ios_base &",
"scientific":"std::ios_base &",
"hexfloat":"std::ios_base &",
"defaultfloat":"std::ios_base &",
"__copy_streambufs_eof":[("std::streamsize","(basic_streambuf<_CharT, _Traits> *, basic_streambuf<_CharT, _Traits> *, bool &)"),("std::streamsize","(basic_streambuf<char> *, basic_streambuf<char> *, bool &)"),("std::streamsize","(basic_streambuf<wchar_t> *, basic_streambuf<wchar_t> *, bool &)")],
"__istream_extract":[("void","(std::istream &, char *, std::streamsize)"),("void","(std::istream &, char *, std::streamsize)")],
"__convert_to_v":[("void","(const char *, float &, ios_base::iostate &, const std::__c_locale &)"),("void","(const char *, double &, ios_base::iostate &, const std::__c_locale &)"),("void","(const char *, long double &, ios_base::iostate &, const std::__c_locale &)")],
"__verify_grouping":"bool",
"__complex_abs":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 615, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 618, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 621, column 3>")],
"__complex_arg":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 642, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 645, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 648, column 3>")],
"__complex_cos":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 726, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 729, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 732, column 3>")],
"__complex_cosh":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 756, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 759, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 762, column 3>")],
"__complex_exp":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 782, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 785, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 788, column 3>")],
"__complex_log":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 809, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 812, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 815, column 3>")],
"__complex_sin":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 844, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 847, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 850, column 3>")],
"__complex_sinh":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 874, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 877, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 880, column 3>")],
"__complex_sqrt":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 918, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 921, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 924, column 3>")],
"__complex_tan":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 945, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 948, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 951, column 3>")],
"__complex_tanh":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 973, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 976, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 979, column 3>")],
"__complex_pow":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1048, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1052, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1056, column 3>")],
"__complex_acos":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1617, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1621, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1625, column 3>")],
"__complex_asin":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1653, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1657, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1661, column 3>")],
"__complex_atan":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1697, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1701, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1705, column 3>")],
"__complex_acosh":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1733, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1737, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1741, column 3>")],
"__complex_asinh":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1772, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1776, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1780, column 3>")],
"__complex_atanh":[("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1816, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1820, column 3>"),("void *","<SourceLocation file '/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/complex', line 1824, column 3>")],
"__complex_proj":[("complex<float>","(const complex<float> &)"),("complex<double>","(const complex<double> &)"),("complex<long double>","(const complex<long double> &)")],
"feclearexcept":"int",
"fegetexceptflag":"int",
"feraiseexcept":"int",
"fesetexcept":"int",
"fesetexceptflag":"int",
"fetestexcept":"int",
"fetestexceptflag":"int",
"fegetround":"int",
"fesetround":"int",
"fegetenv":"int",
"feholdexcept":"int",
"fesetenv":"int",
"feupdateenv":"int",
"fegetmode":"int",
"fesetmode":"int",
"feenableexcept":"int",
"fedisableexcept":"int",
"fegetexcept":"int",
"imaxabs":"intmax_t",
"imaxdiv":"imaxdiv_t",
"strtoimax":"intmax_t",
"strtoumax":"uintmax_t",
"wcstoimax":"intmax_t",
"wcstoumax":"uintmax_t",
"mbrtoc16":"size_t",
"c16rtomb":"size_t",
"mbrtoc32":"size_t",
"c32rtomb":"size_t",
"__deque_buf_size":"std::size_t",
"gettext":"char *",
"dgettext":"char *",
"__dgettext":"char *",
"dcgettext":"char *",
"__dcgettext":"char *",
"ngettext":"char *",
"dngettext":"char *",
"dcngettext":"char *",
"textdomain":"char *",
"bindtextdomain":"char *",
"bind_textdomain_codeset":"char *",
"resetiosflags":"std::_Resetiosflags",
"setiosflags":"std::_Setiosflags",
"setbase":"std::_Setbase",
"setprecision":"std::_Setprecision",
"setw":"std::_Setw",
"_Rb_tree_increment":[("std::_Rb_tree_node_base *","(std::_Rb_tree_node_base *)"),("const std::_Rb_tree_node_base *","(const std::_Rb_tree_node_base *)")],
"_Rb_tree_decrement":[("std::_Rb_tree_node_base *","(std::_Rb_tree_node_base *)"),("const std::_Rb_tree_node_base *","(const std::_Rb_tree_node_base *)")],
"_Rb_tree_insert_and_rebalance":"void",
"_Rb_tree_rebalance_for_erase":"std::_Rb_tree_node_base *",
"_Rb_tree_black_count":"unsigned int",
"align":"void *",
"__throw_concurrence_lock_error":"void",
"__throw_concurrence_unlock_error":"void",
"__throw_concurrence_broadcast_error":"void",
"__throw_concurrence_wait_error":"void",
"__throw_bad_weak_ptr":"void",
"__enable_shared_from_this_base":[("const __enable_shared_from_this<_Tp, _Lp> *","(const __shared_count<_Lp> &, const __enable_shared_from_this<_Tp, _Lp> *)"),("const enable_shared_from_this<_Tp> *","(const __shared_count<> &, const enable_shared_from_this<_Tp> *)")],
"__cmpexch_failure_order2":"std::memory_order",
"__cmpexch_failure_order":"std::memory_order",
"atomic_thread_fence":"void",
"atomic_signal_fence":"void",
"declare_reachable":"void",
"declare_no_pointers":"void",
"undeclare_no_pointers":"void",
"get_pointer_safety":"std::pointer_safety",
"__fill_bvector":"void",
"__valarray_release_memory":"void",
"atomic_flag_test_and_set_explicit":[("bool","(std::atomic_flag *, std::memory_order)"),("bool","(volatile std::atomic_flag *, std::memory_order)")],
"atomic_flag_clear_explicit":[("void","(std::atomic_flag *, std::memory_order)"),("void","(volatile std::atomic_flag *, std::memory_order)")],
"atomic_flag_test_and_set":[("bool","(std::atomic_flag *)"),("bool","(volatile std::atomic_flag *)")],
"atomic_flag_clear":[("void","(std::atomic_flag *)"),("void","(volatile std::atomic_flag *)")],
"notify_all_at_thread_exit":"void",
"__once_proxy":"void",
"get_id":"thread::id",
"yield":"void",
"future_category":"const std::_V2::error_category &",
"__throw_regex_error":[("void","(regex_constants::error_type, const char *)"),("void","(regex_constants::error_type)"),("void","(regex_constants::error_type, const char *)")],
"__clp2":"std::size_t",
"__glibcxx_rwlock_rdlock":"int",
"__glibcxx_rwlock_tryrdlock":"int",
"__glibcxx_rwlock_wrlock":"int",
"__glibcxx_rwlock_trywrlock":"int",
"__glibcxx_rwlock_unlock":"int",
"__glibcxx_rwlock_timedrdlock":"int",
"__glibcxx_rwlock_timedwrlock":"int",

  }

